package cn.net.withub.ums.entity;

import java.util.Date;

public class UmsDegreeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_degree_info.id
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_degree_info.user_id
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_degree_info.old_id
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private Long oldId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_degree_info.sort_no
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private Integer sortNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_degree_info.court_no
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private Integer courtNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_degree_info.user_no
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private Integer userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_degree_info.court_code
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private String courtCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_degree_info.n_degree
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private String nDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_degree_info.n_major
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private Integer nMajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_degree_info.c_major
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private String cMajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_degree_info.c_college
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private String cCollege;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_degree_info.d_graduate_date
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private Date dGraduateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_degree_info.n_present_info
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private Integer nPresentInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_degree_info.n_educate_form
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private Integer nEducateForm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_degree_info.n_study_form
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private String nStudyForm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_degree_info.n_school_type
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private Integer nSchoolType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_degree_info.d_entry_date
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private Date dEntryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_degree_info.n_duration
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private Integer nDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_degree_info.d_award_date
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private Date dAwardDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_degree_info.n_award_country
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private String nAwardCountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_degree_info.n_sync
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private Integer nSync;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_degree_info.record_id
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private String recordId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_degree_info.id
     *
     * @return the value of ums_degree_info.id
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_degree_info.id
     *
     * @param id the value for ums_degree_info.id
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_degree_info.user_id
     *
     * @return the value of ums_degree_info.user_id
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_degree_info.user_id
     *
     * @param userId the value for ums_degree_info.user_id
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_degree_info.old_id
     *
     * @return the value of ums_degree_info.old_id
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public Long getOldId() {
        return oldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_degree_info.old_id
     *
     * @param oldId the value for ums_degree_info.old_id
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setOldId(Long oldId) {
        this.oldId = oldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_degree_info.sort_no
     *
     * @return the value of ums_degree_info.sort_no
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public Integer getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_degree_info.sort_no
     *
     * @param sortNo the value for ums_degree_info.sort_no
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setSortNo(Integer sortNo) {
        this.sortNo = sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_degree_info.court_no
     *
     * @return the value of ums_degree_info.court_no
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public Integer getCourtNo() {
        return courtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_degree_info.court_no
     *
     * @param courtNo the value for ums_degree_info.court_no
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setCourtNo(Integer courtNo) {
        this.courtNo = courtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_degree_info.user_no
     *
     * @return the value of ums_degree_info.user_no
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public Integer getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_degree_info.user_no
     *
     * @param userNo the value for ums_degree_info.user_no
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setUserNo(Integer userNo) {
        this.userNo = userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_degree_info.court_code
     *
     * @return the value of ums_degree_info.court_code
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public String getCourtCode() {
        return courtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_degree_info.court_code
     *
     * @param courtCode the value for ums_degree_info.court_code
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setCourtCode(String courtCode) {
        this.courtCode = courtCode == null ? null : courtCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_degree_info.n_degree
     *
     * @return the value of ums_degree_info.n_degree
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public String getnDegree() {
        return nDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_degree_info.n_degree
     *
     * @param nDegree the value for ums_degree_info.n_degree
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setnDegree(String nDegree) {
        this.nDegree = nDegree == null ? null : nDegree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_degree_info.n_major
     *
     * @return the value of ums_degree_info.n_major
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public Integer getnMajor() {
        return nMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_degree_info.n_major
     *
     * @param nMajor the value for ums_degree_info.n_major
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setnMajor(Integer nMajor) {
        this.nMajor = nMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_degree_info.c_major
     *
     * @return the value of ums_degree_info.c_major
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public String getcMajor() {
        return cMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_degree_info.c_major
     *
     * @param cMajor the value for ums_degree_info.c_major
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setcMajor(String cMajor) {
        this.cMajor = cMajor == null ? null : cMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_degree_info.c_college
     *
     * @return the value of ums_degree_info.c_college
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public String getcCollege() {
        return cCollege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_degree_info.c_college
     *
     * @param cCollege the value for ums_degree_info.c_college
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setcCollege(String cCollege) {
        this.cCollege = cCollege == null ? null : cCollege.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_degree_info.d_graduate_date
     *
     * @return the value of ums_degree_info.d_graduate_date
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public Date getdGraduateDate() {
        return dGraduateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_degree_info.d_graduate_date
     *
     * @param dGraduateDate the value for ums_degree_info.d_graduate_date
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setdGraduateDate(Date dGraduateDate) {
        this.dGraduateDate = dGraduateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_degree_info.n_present_info
     *
     * @return the value of ums_degree_info.n_present_info
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public Integer getnPresentInfo() {
        return nPresentInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_degree_info.n_present_info
     *
     * @param nPresentInfo the value for ums_degree_info.n_present_info
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setnPresentInfo(Integer nPresentInfo) {
        this.nPresentInfo = nPresentInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_degree_info.n_educate_form
     *
     * @return the value of ums_degree_info.n_educate_form
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public Integer getnEducateForm() {
        return nEducateForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_degree_info.n_educate_form
     *
     * @param nEducateForm the value for ums_degree_info.n_educate_form
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setnEducateForm(Integer nEducateForm) {
        this.nEducateForm = nEducateForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_degree_info.n_study_form
     *
     * @return the value of ums_degree_info.n_study_form
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public String getnStudyForm() {
        return nStudyForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_degree_info.n_study_form
     *
     * @param nStudyForm the value for ums_degree_info.n_study_form
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setnStudyForm(String nStudyForm) {
        this.nStudyForm = nStudyForm == null ? null : nStudyForm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_degree_info.n_school_type
     *
     * @return the value of ums_degree_info.n_school_type
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public Integer getnSchoolType() {
        return nSchoolType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_degree_info.n_school_type
     *
     * @param nSchoolType the value for ums_degree_info.n_school_type
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setnSchoolType(Integer nSchoolType) {
        this.nSchoolType = nSchoolType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_degree_info.d_entry_date
     *
     * @return the value of ums_degree_info.d_entry_date
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public Date getdEntryDate() {
        return dEntryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_degree_info.d_entry_date
     *
     * @param dEntryDate the value for ums_degree_info.d_entry_date
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setdEntryDate(Date dEntryDate) {
        this.dEntryDate = dEntryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_degree_info.n_duration
     *
     * @return the value of ums_degree_info.n_duration
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public Integer getnDuration() {
        return nDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_degree_info.n_duration
     *
     * @param nDuration the value for ums_degree_info.n_duration
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setnDuration(Integer nDuration) {
        this.nDuration = nDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_degree_info.d_award_date
     *
     * @return the value of ums_degree_info.d_award_date
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public Date getdAwardDate() {
        return dAwardDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_degree_info.d_award_date
     *
     * @param dAwardDate the value for ums_degree_info.d_award_date
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setdAwardDate(Date dAwardDate) {
        this.dAwardDate = dAwardDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_degree_info.n_award_country
     *
     * @return the value of ums_degree_info.n_award_country
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public String getnAwardCountry() {
        return nAwardCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_degree_info.n_award_country
     *
     * @param nAwardCountry the value for ums_degree_info.n_award_country
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setnAwardCountry(String nAwardCountry) {
        this.nAwardCountry = nAwardCountry == null ? null : nAwardCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_degree_info.n_sync
     *
     * @return the value of ums_degree_info.n_sync
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public Integer getnSync() {
        return nSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_degree_info.n_sync
     *
     * @param nSync the value for ums_degree_info.n_sync
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setnSync(Integer nSync) {
        this.nSync = nSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_degree_info.record_id
     *
     * @return the value of ums_degree_info.record_id
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_degree_info.record_id
     *
     * @param recordId the value for ums_degree_info.record_id
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId == null ? null : recordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_degree_info
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UmsDegreeInfo other = (UmsDegreeInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getOldId() == null ? other.getOldId() == null : this.getOldId().equals(other.getOldId()))
            && (this.getSortNo() == null ? other.getSortNo() == null : this.getSortNo().equals(other.getSortNo()))
            && (this.getCourtNo() == null ? other.getCourtNo() == null : this.getCourtNo().equals(other.getCourtNo()))
            && (this.getUserNo() == null ? other.getUserNo() == null : this.getUserNo().equals(other.getUserNo()))
            && (this.getCourtCode() == null ? other.getCourtCode() == null : this.getCourtCode().equals(other.getCourtCode()))
            && (this.getnDegree() == null ? other.getnDegree() == null : this.getnDegree().equals(other.getnDegree()))
            && (this.getnMajor() == null ? other.getnMajor() == null : this.getnMajor().equals(other.getnMajor()))
            && (this.getcMajor() == null ? other.getcMajor() == null : this.getcMajor().equals(other.getcMajor()))
            && (this.getcCollege() == null ? other.getcCollege() == null : this.getcCollege().equals(other.getcCollege()))
            && (this.getdGraduateDate() == null ? other.getdGraduateDate() == null : this.getdGraduateDate().equals(other.getdGraduateDate()))
            && (this.getnPresentInfo() == null ? other.getnPresentInfo() == null : this.getnPresentInfo().equals(other.getnPresentInfo()))
            && (this.getnEducateForm() == null ? other.getnEducateForm() == null : this.getnEducateForm().equals(other.getnEducateForm()))
            && (this.getnStudyForm() == null ? other.getnStudyForm() == null : this.getnStudyForm().equals(other.getnStudyForm()))
            && (this.getnSchoolType() == null ? other.getnSchoolType() == null : this.getnSchoolType().equals(other.getnSchoolType()))
            && (this.getdEntryDate() == null ? other.getdEntryDate() == null : this.getdEntryDate().equals(other.getdEntryDate()))
            && (this.getnDuration() == null ? other.getnDuration() == null : this.getnDuration().equals(other.getnDuration()))
            && (this.getdAwardDate() == null ? other.getdAwardDate() == null : this.getdAwardDate().equals(other.getdAwardDate()))
            && (this.getnAwardCountry() == null ? other.getnAwardCountry() == null : this.getnAwardCountry().equals(other.getnAwardCountry()))
            && (this.getnSync() == null ? other.getnSync() == null : this.getnSync().equals(other.getnSync()))
            && (this.getRecordId() == null ? other.getRecordId() == null : this.getRecordId().equals(other.getRecordId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_degree_info
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getOldId() == null) ? 0 : getOldId().hashCode());
        result = prime * result + ((getSortNo() == null) ? 0 : getSortNo().hashCode());
        result = prime * result + ((getCourtNo() == null) ? 0 : getCourtNo().hashCode());
        result = prime * result + ((getUserNo() == null) ? 0 : getUserNo().hashCode());
        result = prime * result + ((getCourtCode() == null) ? 0 : getCourtCode().hashCode());
        result = prime * result + ((getnDegree() == null) ? 0 : getnDegree().hashCode());
        result = prime * result + ((getnMajor() == null) ? 0 : getnMajor().hashCode());
        result = prime * result + ((getcMajor() == null) ? 0 : getcMajor().hashCode());
        result = prime * result + ((getcCollege() == null) ? 0 : getcCollege().hashCode());
        result = prime * result + ((getdGraduateDate() == null) ? 0 : getdGraduateDate().hashCode());
        result = prime * result + ((getnPresentInfo() == null) ? 0 : getnPresentInfo().hashCode());
        result = prime * result + ((getnEducateForm() == null) ? 0 : getnEducateForm().hashCode());
        result = prime * result + ((getnStudyForm() == null) ? 0 : getnStudyForm().hashCode());
        result = prime * result + ((getnSchoolType() == null) ? 0 : getnSchoolType().hashCode());
        result = prime * result + ((getdEntryDate() == null) ? 0 : getdEntryDate().hashCode());
        result = prime * result + ((getnDuration() == null) ? 0 : getnDuration().hashCode());
        result = prime * result + ((getdAwardDate() == null) ? 0 : getdAwardDate().hashCode());
        result = prime * result + ((getnAwardCountry() == null) ? 0 : getnAwardCountry().hashCode());
        result = prime * result + ((getnSync() == null) ? 0 : getnSync().hashCode());
        result = prime * result + ((getRecordId() == null) ? 0 : getRecordId().hashCode());
        return result;
    }
}