package cn.net.withub.ums.entity;

import java.util.Date;

public class UmsExternalLabourContract {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_extenal_labour_contract.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_extenal_labour_contract.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_extenal_labour_contract.contract_start
     *
     * @mbggenerated
     */
    private Date contractStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_extenal_labour_contract.contract_end
     *
     * @mbggenerated
     */
    private Date contractEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_extenal_labour_contract.contract_nature
     *
     * @mbggenerated
     */
    private String contractNature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_extenal_labour_contract.contract_company
     *
     * @mbggenerated
     */
    private String contractCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_extenal_labour_contract.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_extenal_labour_contract.update_date
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_extenal_labour_contract.sort_no
     *
     * @mbggenerated
     */
    private Integer sortNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_extenal_labour_contract.id
     *
     * @return the value of ums_extenal_labour_contract.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_extenal_labour_contract.id
     *
     * @param id the value for ums_extenal_labour_contract.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_extenal_labour_contract.user_id
     *
     * @return the value of ums_extenal_labour_contract.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_extenal_labour_contract.user_id
     *
     * @param userId the value for ums_extenal_labour_contract.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_extenal_labour_contract.contract_start
     *
     * @return the value of ums_extenal_labour_contract.contract_start
     *
     * @mbggenerated
     */
    public Date getContractStart() {
        return contractStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_extenal_labour_contract.contract_start
     *
     * @param contractStart the value for ums_extenal_labour_contract.contract_start
     *
     * @mbggenerated
     */
    public void setContractStart(Date contractStart) {
        this.contractStart = contractStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_extenal_labour_contract.contract_end
     *
     * @return the value of ums_extenal_labour_contract.contract_end
     *
     * @mbggenerated
     */
    public Date getContractEnd() {
        return contractEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_extenal_labour_contract.contract_end
     *
     * @param contractEnd the value for ums_extenal_labour_contract.contract_end
     *
     * @mbggenerated
     */
    public void setContractEnd(Date contractEnd) {
        this.contractEnd = contractEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_extenal_labour_contract.contract_nature
     *
     * @return the value of ums_extenal_labour_contract.contract_nature
     *
     * @mbggenerated
     */
    public String getContractNature() {
        return contractNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_extenal_labour_contract.contract_nature
     *
     * @param contractNature the value for ums_extenal_labour_contract.contract_nature
     *
     * @mbggenerated
     */
    public void setContractNature(String contractNature) {
        this.contractNature = contractNature == null ? null : contractNature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_extenal_labour_contract.contract_company
     *
     * @return the value of ums_extenal_labour_contract.contract_company
     *
     * @mbggenerated
     */
    public String getContractCompany() {
        return contractCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_extenal_labour_contract.contract_company
     *
     * @param contractCompany the value for ums_extenal_labour_contract.contract_company
     *
     * @mbggenerated
     */
    public void setContractCompany(String contractCompany) {
        this.contractCompany = contractCompany == null ? null : contractCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_extenal_labour_contract.update_user
     *
     * @return the value of ums_extenal_labour_contract.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_extenal_labour_contract.update_user
     *
     * @param updateUser the value for ums_extenal_labour_contract.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_extenal_labour_contract.update_date
     *
     * @return the value of ums_extenal_labour_contract.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_extenal_labour_contract.update_date
     *
     * @param updateTime the value for ums_extenal_labour_contract.update_date
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_extenal_labour_contract.sort_no
     *
     * @return the value of ums_extenal_labour_contract.sort_no
     *
     * @mbggenerated
     */
    public Integer getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_extenal_labour_contract.sort_no
     *
     * @param sortNo the value for ums_extenal_labour_contract.sort_no
     *
     * @mbggenerated
     */
    public void setSortNo(Integer sortNo) {
        this.sortNo = sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_extenal_labour_contract
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UmsExternalLabourContract other = (UmsExternalLabourContract) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getContractStart() == null ? other.getContractStart() == null : this.getContractStart().equals(other.getContractStart()))
            && (this.getContractEnd() == null ? other.getContractEnd() == null : this.getContractEnd().equals(other.getContractEnd()))
            && (this.getContractNature() == null ? other.getContractNature() == null : this.getContractNature().equals(other.getContractNature()))
            && (this.getContractCompany() == null ? other.getContractCompany() == null : this.getContractCompany().equals(other.getContractCompany()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getSortNo() == null ? other.getSortNo() == null : this.getSortNo().equals(other.getSortNo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_extenal_labour_contract
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getContractStart() == null) ? 0 : getContractStart().hashCode());
        result = prime * result + ((getContractEnd() == null) ? 0 : getContractEnd().hashCode());
        result = prime * result + ((getContractNature() == null) ? 0 : getContractNature().hashCode());
        result = prime * result + ((getContractCompany() == null) ? 0 : getContractCompany().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getSortNo() == null) ? 0 : getSortNo().hashCode());
        return result;
    }


    @Override
    public String toString() {
        return "UmsExternalLabourContract{" +
                "id='" + id + '\'' +
                ", userId='" + userId + '\'' +
                ", contractStart=" + contractStart +
                ", contractEnd=" + contractEnd +
                ", contractNature='" + contractNature + '\'' +
                ", contractCompany='" + contractCompany + '\'' +
                ", updateUser='" + updateUser + '\'' +
                ", updateTime=" + updateTime +
                ", sortNo=" + sortNo +
                '}';
    }
}