package cn.net.withub.ums.entity;

public class UmsFieldContrastKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_field_contrast.source_table
     *
     * @mbggenerated Mon Jan 18 11:15:50 CST 2016
     */
    private String sourceTable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_field_contrast.source_field
     *
     * @mbggenerated Mon Jan 18 11:15:50 CST 2016
     */
    private String sourceField;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_field_contrast.source_table
     *
     * @return the value of ums_field_contrast.source_table
     *
     * @mbggenerated Mon Jan 18 11:15:50 CST 2016
     */
    public String getSourceTable() {
        return sourceTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_field_contrast.source_table
     *
     * @param sourceTable the value for ums_field_contrast.source_table
     *
     * @mbggenerated Mon Jan 18 11:15:50 CST 2016
     */
    public void setSourceTable(String sourceTable) {
        this.sourceTable = sourceTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_field_contrast.source_field
     *
     * @return the value of ums_field_contrast.source_field
     *
     * @mbggenerated Mon Jan 18 11:15:50 CST 2016
     */
    public String getSourceField() {
        return sourceField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_field_contrast.source_field
     *
     * @param sourceField the value for ums_field_contrast.source_field
     *
     * @mbggenerated Mon Jan 18 11:15:50 CST 2016
     */
    public void setSourceField(String sourceField) {
        this.sourceField = sourceField;
    }
}
