package cn.net.withub.ums.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class UmsLegalJobCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public UmsLegalJobCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andOldIdIsNull() {
            addCriterion("old_id is null");
            return (Criteria) this;
        }

        public Criteria andOldIdIsNotNull() {
            addCriterion("old_id is not null");
            return (Criteria) this;
        }

        public Criteria andOldIdEqualTo(Long value) {
            addCriterion("old_id =", value, "oldId");
            return (Criteria) this;
        }

        public Criteria andOldIdNotEqualTo(Long value) {
            addCriterion("old_id <>", value, "oldId");
            return (Criteria) this;
        }

        public Criteria andOldIdGreaterThan(Long value) {
            addCriterion("old_id >", value, "oldId");
            return (Criteria) this;
        }

        public Criteria andOldIdGreaterThanOrEqualTo(Long value) {
            addCriterion("old_id >=", value, "oldId");
            return (Criteria) this;
        }

        public Criteria andOldIdLessThan(Long value) {
            addCriterion("old_id <", value, "oldId");
            return (Criteria) this;
        }

        public Criteria andOldIdLessThanOrEqualTo(Long value) {
            addCriterion("old_id <=", value, "oldId");
            return (Criteria) this;
        }

        public Criteria andOldIdIn(List<Long> values) {
            addCriterion("old_id in", values, "oldId");
            return (Criteria) this;
        }

        public Criteria andOldIdNotIn(List<Long> values) {
            addCriterion("old_id not in", values, "oldId");
            return (Criteria) this;
        }

        public Criteria andOldIdBetween(Long value1, Long value2) {
            addCriterion("old_id between", value1, value2, "oldId");
            return (Criteria) this;
        }

        public Criteria andOldIdNotBetween(Long value1, Long value2) {
            addCriterion("old_id not between", value1, value2, "oldId");
            return (Criteria) this;
        }

        public Criteria andCourtNoIsNull() {
            addCriterion("court_no is null");
            return (Criteria) this;
        }

        public Criteria andCourtNoIsNotNull() {
            addCriterion("court_no is not null");
            return (Criteria) this;
        }

        public Criteria andCourtNoEqualTo(Integer value) {
            addCriterion("court_no =", value, "courtNo");
            return (Criteria) this;
        }

        public Criteria andCourtNoNotEqualTo(Integer value) {
            addCriterion("court_no <>", value, "courtNo");
            return (Criteria) this;
        }

        public Criteria andCourtNoGreaterThan(Integer value) {
            addCriterion("court_no >", value, "courtNo");
            return (Criteria) this;
        }

        public Criteria andCourtNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("court_no >=", value, "courtNo");
            return (Criteria) this;
        }

        public Criteria andCourtNoLessThan(Integer value) {
            addCriterion("court_no <", value, "courtNo");
            return (Criteria) this;
        }

        public Criteria andCourtNoLessThanOrEqualTo(Integer value) {
            addCriterion("court_no <=", value, "courtNo");
            return (Criteria) this;
        }

        public Criteria andCourtNoIn(List<Integer> values) {
            addCriterion("court_no in", values, "courtNo");
            return (Criteria) this;
        }

        public Criteria andCourtNoNotIn(List<Integer> values) {
            addCriterion("court_no not in", values, "courtNo");
            return (Criteria) this;
        }

        public Criteria andCourtNoBetween(Integer value1, Integer value2) {
            addCriterion("court_no between", value1, value2, "courtNo");
            return (Criteria) this;
        }

        public Criteria andCourtNoNotBetween(Integer value1, Integer value2) {
            addCriterion("court_no not between", value1, value2, "courtNo");
            return (Criteria) this;
        }

        public Criteria andUserNoIsNull() {
            addCriterion("user_no is null");
            return (Criteria) this;
        }

        public Criteria andUserNoIsNotNull() {
            addCriterion("user_no is not null");
            return (Criteria) this;
        }

        public Criteria andUserNoEqualTo(Integer value) {
            addCriterion("user_no =", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoNotEqualTo(Integer value) {
            addCriterion("user_no <>", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoGreaterThan(Integer value) {
            addCriterion("user_no >", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_no >=", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoLessThan(Integer value) {
            addCriterion("user_no <", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoLessThanOrEqualTo(Integer value) {
            addCriterion("user_no <=", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoIn(List<Integer> values) {
            addCriterion("user_no in", values, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoNotIn(List<Integer> values) {
            addCriterion("user_no not in", values, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoBetween(Integer value1, Integer value2) {
            addCriterion("user_no between", value1, value2, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoNotBetween(Integer value1, Integer value2) {
            addCriterion("user_no not between", value1, value2, "userNo");
            return (Criteria) this;
        }

        public Criteria andSortNoIsNull() {
            addCriterion("sort_no is null");
            return (Criteria) this;
        }

        public Criteria andSortNoIsNotNull() {
            addCriterion("sort_no is not null");
            return (Criteria) this;
        }

        public Criteria andSortNoEqualTo(Integer value) {
            addCriterion("sort_no =", value, "sortNo");
            return (Criteria) this;
        }

        public Criteria andSortNoNotEqualTo(Integer value) {
            addCriterion("sort_no <>", value, "sortNo");
            return (Criteria) this;
        }

        public Criteria andSortNoGreaterThan(Integer value) {
            addCriterion("sort_no >", value, "sortNo");
            return (Criteria) this;
        }

        public Criteria andSortNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("sort_no >=", value, "sortNo");
            return (Criteria) this;
        }

        public Criteria andSortNoLessThan(Integer value) {
            addCriterion("sort_no <", value, "sortNo");
            return (Criteria) this;
        }

        public Criteria andSortNoLessThanOrEqualTo(Integer value) {
            addCriterion("sort_no <=", value, "sortNo");
            return (Criteria) this;
        }

        public Criteria andSortNoIn(List<Integer> values) {
            addCriterion("sort_no in", values, "sortNo");
            return (Criteria) this;
        }

        public Criteria andSortNoNotIn(List<Integer> values) {
            addCriterion("sort_no not in", values, "sortNo");
            return (Criteria) this;
        }

        public Criteria andSortNoBetween(Integer value1, Integer value2) {
            addCriterion("sort_no between", value1, value2, "sortNo");
            return (Criteria) this;
        }

        public Criteria andSortNoNotBetween(Integer value1, Integer value2) {
            addCriterion("sort_no not between", value1, value2, "sortNo");
            return (Criteria) this;
        }

        public Criteria andNAssignTypeIsNull() {
            addCriterion("n_assign_type is null");
            return (Criteria) this;
        }

        public Criteria andNAssignTypeIsNotNull() {
            addCriterion("n_assign_type is not null");
            return (Criteria) this;
        }

        public Criteria andNAssignTypeEqualTo(Integer value) {
            addCriterion("n_assign_type =", value, "nAssignType");
            return (Criteria) this;
        }

        public Criteria andNAssignTypeNotEqualTo(Integer value) {
            addCriterion("n_assign_type <>", value, "nAssignType");
            return (Criteria) this;
        }

        public Criteria andNAssignTypeGreaterThan(Integer value) {
            addCriterion("n_assign_type >", value, "nAssignType");
            return (Criteria) this;
        }

        public Criteria andNAssignTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("n_assign_type >=", value, "nAssignType");
            return (Criteria) this;
        }

        public Criteria andNAssignTypeLessThan(Integer value) {
            addCriterion("n_assign_type <", value, "nAssignType");
            return (Criteria) this;
        }

        public Criteria andNAssignTypeLessThanOrEqualTo(Integer value) {
            addCriterion("n_assign_type <=", value, "nAssignType");
            return (Criteria) this;
        }

        public Criteria andNAssignTypeIn(List<Integer> values) {
            addCriterion("n_assign_type in", values, "nAssignType");
            return (Criteria) this;
        }

        public Criteria andNAssignTypeNotIn(List<Integer> values) {
            addCriterion("n_assign_type not in", values, "nAssignType");
            return (Criteria) this;
        }

        public Criteria andNAssignTypeBetween(Integer value1, Integer value2) {
            addCriterion("n_assign_type between", value1, value2, "nAssignType");
            return (Criteria) this;
        }

        public Criteria andNAssignTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("n_assign_type not between", value1, value2, "nAssignType");
            return (Criteria) this;
        }

        public Criteria andCUnitIsNull() {
            addCriterion("c_unit is null");
            return (Criteria) this;
        }

        public Criteria andCUnitIsNotNull() {
            addCriterion("c_unit is not null");
            return (Criteria) this;
        }

        public Criteria andCUnitEqualTo(String value) {
            addCriterion("c_unit =", value, "cUnit");
            return (Criteria) this;
        }

        public Criteria andCUnitNotEqualTo(String value) {
            addCriterion("c_unit <>", value, "cUnit");
            return (Criteria) this;
        }

        public Criteria andCUnitGreaterThan(String value) {
            addCriterion("c_unit >", value, "cUnit");
            return (Criteria) this;
        }

        public Criteria andCUnitGreaterThanOrEqualTo(String value) {
            addCriterion("c_unit >=", value, "cUnit");
            return (Criteria) this;
        }

        public Criteria andCUnitLessThan(String value) {
            addCriterion("c_unit <", value, "cUnit");
            return (Criteria) this;
        }

        public Criteria andCUnitLessThanOrEqualTo(String value) {
            addCriterion("c_unit <=", value, "cUnit");
            return (Criteria) this;
        }

        public Criteria andCUnitLike(String value) {
            addCriterion("c_unit like", value, "cUnit");
            return (Criteria) this;
        }

        public Criteria andCUnitNotLike(String value) {
            addCriterion("c_unit not like", value, "cUnit");
            return (Criteria) this;
        }

        public Criteria andCUnitIn(List<String> values) {
            addCriterion("c_unit in", values, "cUnit");
            return (Criteria) this;
        }

        public Criteria andCUnitNotIn(List<String> values) {
            addCriterion("c_unit not in", values, "cUnit");
            return (Criteria) this;
        }

        public Criteria andCUnitBetween(String value1, String value2) {
            addCriterion("c_unit between", value1, value2, "cUnit");
            return (Criteria) this;
        }

        public Criteria andCUnitNotBetween(String value1, String value2) {
            addCriterion("c_unit not between", value1, value2, "cUnit");
            return (Criteria) this;
        }

        public Criteria andCDepartmentIsNull() {
            addCriterion("c_department is null");
            return (Criteria) this;
        }

        public Criteria andCDepartmentIsNotNull() {
            addCriterion("c_department is not null");
            return (Criteria) this;
        }

        public Criteria andCDepartmentEqualTo(String value) {
            addCriterion("c_department =", value, "cDepartment");
            return (Criteria) this;
        }

        public Criteria andCDepartmentNotEqualTo(String value) {
            addCriterion("c_department <>", value, "cDepartment");
            return (Criteria) this;
        }

        public Criteria andCDepartmentGreaterThan(String value) {
            addCriterion("c_department >", value, "cDepartment");
            return (Criteria) this;
        }

        public Criteria andCDepartmentGreaterThanOrEqualTo(String value) {
            addCriterion("c_department >=", value, "cDepartment");
            return (Criteria) this;
        }

        public Criteria andCDepartmentLessThan(String value) {
            addCriterion("c_department <", value, "cDepartment");
            return (Criteria) this;
        }

        public Criteria andCDepartmentLessThanOrEqualTo(String value) {
            addCriterion("c_department <=", value, "cDepartment");
            return (Criteria) this;
        }

        public Criteria andCDepartmentLike(String value) {
            addCriterion("c_department like", value, "cDepartment");
            return (Criteria) this;
        }

        public Criteria andCDepartmentNotLike(String value) {
            addCriterion("c_department not like", value, "cDepartment");
            return (Criteria) this;
        }

        public Criteria andCDepartmentIn(List<String> values) {
            addCriterion("c_department in", values, "cDepartment");
            return (Criteria) this;
        }

        public Criteria andCDepartmentNotIn(List<String> values) {
            addCriterion("c_department not in", values, "cDepartment");
            return (Criteria) this;
        }

        public Criteria andCDepartmentBetween(String value1, String value2) {
            addCriterion("c_department between", value1, value2, "cDepartment");
            return (Criteria) this;
        }

        public Criteria andCDepartmentNotBetween(String value1, String value2) {
            addCriterion("c_department not between", value1, value2, "cDepartment");
            return (Criteria) this;
        }

        public Criteria andNAssignReasonIsNull() {
            addCriterion("n_assign_reason is null");
            return (Criteria) this;
        }

        public Criteria andNAssignReasonIsNotNull() {
            addCriterion("n_assign_reason is not null");
            return (Criteria) this;
        }

        public Criteria andNAssignReasonEqualTo(Integer value) {
            addCriterion("n_assign_reason =", value, "nAssignReason");
            return (Criteria) this;
        }

        public Criteria andNAssignReasonNotEqualTo(Integer value) {
            addCriterion("n_assign_reason <>", value, "nAssignReason");
            return (Criteria) this;
        }

        public Criteria andNAssignReasonGreaterThan(Integer value) {
            addCriterion("n_assign_reason >", value, "nAssignReason");
            return (Criteria) this;
        }

        public Criteria andNAssignReasonGreaterThanOrEqualTo(Integer value) {
            addCriterion("n_assign_reason >=", value, "nAssignReason");
            return (Criteria) this;
        }

        public Criteria andNAssignReasonLessThan(Integer value) {
            addCriterion("n_assign_reason <", value, "nAssignReason");
            return (Criteria) this;
        }

        public Criteria andNAssignReasonLessThanOrEqualTo(Integer value) {
            addCriterion("n_assign_reason <=", value, "nAssignReason");
            return (Criteria) this;
        }

        public Criteria andNAssignReasonIn(List<Integer> values) {
            addCriterion("n_assign_reason in", values, "nAssignReason");
            return (Criteria) this;
        }

        public Criteria andNAssignReasonNotIn(List<Integer> values) {
            addCriterion("n_assign_reason not in", values, "nAssignReason");
            return (Criteria) this;
        }

        public Criteria andNAssignReasonBetween(Integer value1, Integer value2) {
            addCriterion("n_assign_reason between", value1, value2, "nAssignReason");
            return (Criteria) this;
        }

        public Criteria andNAssignReasonNotBetween(Integer value1, Integer value2) {
            addCriterion("n_assign_reason not between", value1, value2, "nAssignReason");
            return (Criteria) this;
        }

        public Criteria andNJobIsNull() {
            addCriterion("n_job is null");
            return (Criteria) this;
        }

        public Criteria andNJobIsNotNull() {
            addCriterion("n_job is not null");
            return (Criteria) this;
        }

        public Criteria andNJobEqualTo(String value) {
            addCriterion("n_job =", value, "nJob");
            return (Criteria) this;
        }

        public Criteria andNJobNotEqualTo(String value) {
            addCriterion("n_job <>", value, "nJob");
            return (Criteria) this;
        }

        public Criteria andNJobGreaterThan(String value) {
            addCriterion("n_job >", value, "nJob");
            return (Criteria) this;
        }

        public Criteria andNJobGreaterThanOrEqualTo(String value) {
            addCriterion("n_job >=", value, "nJob");
            return (Criteria) this;
        }

        public Criteria andNJobLessThan(String value) {
            addCriterion("n_job <", value, "nJob");
            return (Criteria) this;
        }

        public Criteria andNJobLessThanOrEqualTo(String value) {
            addCriterion("n_job <=", value, "nJob");
            return (Criteria) this;
        }

        public Criteria andNJobLike(String value) {
            addCriterion("n_job like", value, "nJob");
            return (Criteria) this;
        }

        public Criteria andNJobNotLike(String value) {
            addCriterion("n_job not like", value, "nJob");
            return (Criteria) this;
        }

        public Criteria andNJobIn(List<String> values) {
            addCriterion("n_job in", values, "nJob");
            return (Criteria) this;
        }

        public Criteria andNJobNotIn(List<String> values) {
            addCriterion("n_job not in", values, "nJob");
            return (Criteria) this;
        }

        public Criteria andNJobBetween(String value1, String value2) {
            addCriterion("n_job between", value1, value2, "nJob");
            return (Criteria) this;
        }

        public Criteria andNJobNotBetween(String value1, String value2) {
            addCriterion("n_job not between", value1, value2, "nJob");
            return (Criteria) this;
        }

        public Criteria andDAssignDateIsNull() {
            addCriterion("d_assign_date is null");
            return (Criteria) this;
        }

        public Criteria andDAssignDateIsNotNull() {
            addCriterion("d_assign_date is not null");
            return (Criteria) this;
        }

        public Criteria andDAssignDateEqualTo(Date value) {
            addCriterionForJDBCDate("d_assign_date =", value, "dAssignDate");
            return (Criteria) this;
        }

        public Criteria andDAssignDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("d_assign_date <>", value, "dAssignDate");
            return (Criteria) this;
        }

        public Criteria andDAssignDateGreaterThan(Date value) {
            addCriterionForJDBCDate("d_assign_date >", value, "dAssignDate");
            return (Criteria) this;
        }

        public Criteria andDAssignDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("d_assign_date >=", value, "dAssignDate");
            return (Criteria) this;
        }

        public Criteria andDAssignDateLessThan(Date value) {
            addCriterionForJDBCDate("d_assign_date <", value, "dAssignDate");
            return (Criteria) this;
        }

        public Criteria andDAssignDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("d_assign_date <=", value, "dAssignDate");
            return (Criteria) this;
        }

        public Criteria andDAssignDateIn(List<Date> values) {
            addCriterionForJDBCDate("d_assign_date in", values, "dAssignDate");
            return (Criteria) this;
        }

        public Criteria andDAssignDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("d_assign_date not in", values, "dAssignDate");
            return (Criteria) this;
        }

        public Criteria andDAssignDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("d_assign_date between", value1, value2, "dAssignDate");
            return (Criteria) this;
        }

        public Criteria andDAssignDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("d_assign_date not between", value1, value2, "dAssignDate");
            return (Criteria) this;
        }

        public Criteria andCApprovalDocNoIsNull() {
            addCriterion("c_approval_doc_no is null");
            return (Criteria) this;
        }

        public Criteria andCApprovalDocNoIsNotNull() {
            addCriterion("c_approval_doc_no is not null");
            return (Criteria) this;
        }

        public Criteria andCApprovalDocNoEqualTo(String value) {
            addCriterion("c_approval_doc_no =", value, "cApprovalDocNo");
            return (Criteria) this;
        }

        public Criteria andCApprovalDocNoNotEqualTo(String value) {
            addCriterion("c_approval_doc_no <>", value, "cApprovalDocNo");
            return (Criteria) this;
        }

        public Criteria andCApprovalDocNoGreaterThan(String value) {
            addCriterion("c_approval_doc_no >", value, "cApprovalDocNo");
            return (Criteria) this;
        }

        public Criteria andCApprovalDocNoGreaterThanOrEqualTo(String value) {
            addCriterion("c_approval_doc_no >=", value, "cApprovalDocNo");
            return (Criteria) this;
        }

        public Criteria andCApprovalDocNoLessThan(String value) {
            addCriterion("c_approval_doc_no <", value, "cApprovalDocNo");
            return (Criteria) this;
        }

        public Criteria andCApprovalDocNoLessThanOrEqualTo(String value) {
            addCriterion("c_approval_doc_no <=", value, "cApprovalDocNo");
            return (Criteria) this;
        }

        public Criteria andCApprovalDocNoLike(String value) {
            addCriterion("c_approval_doc_no like", value, "cApprovalDocNo");
            return (Criteria) this;
        }

        public Criteria andCApprovalDocNoNotLike(String value) {
            addCriterion("c_approval_doc_no not like", value, "cApprovalDocNo");
            return (Criteria) this;
        }

        public Criteria andCApprovalDocNoIn(List<String> values) {
            addCriterion("c_approval_doc_no in", values, "cApprovalDocNo");
            return (Criteria) this;
        }

        public Criteria andCApprovalDocNoNotIn(List<String> values) {
            addCriterion("c_approval_doc_no not in", values, "cApprovalDocNo");
            return (Criteria) this;
        }

        public Criteria andCApprovalDocNoBetween(String value1, String value2) {
            addCriterion("c_approval_doc_no between", value1, value2, "cApprovalDocNo");
            return (Criteria) this;
        }

        public Criteria andCApprovalDocNoNotBetween(String value1, String value2) {
            addCriterion("c_approval_doc_no not between", value1, value2, "cApprovalDocNo");
            return (Criteria) this;
        }

        public Criteria andCApprovalUnitIsNull() {
            addCriterion("c_approval_unit is null");
            return (Criteria) this;
        }

        public Criteria andCApprovalUnitIsNotNull() {
            addCriterion("c_approval_unit is not null");
            return (Criteria) this;
        }

        public Criteria andCApprovalUnitEqualTo(String value) {
            addCriterion("c_approval_unit =", value, "cApprovalUnit");
            return (Criteria) this;
        }

        public Criteria andCApprovalUnitNotEqualTo(String value) {
            addCriterion("c_approval_unit <>", value, "cApprovalUnit");
            return (Criteria) this;
        }

        public Criteria andCApprovalUnitGreaterThan(String value) {
            addCriterion("c_approval_unit >", value, "cApprovalUnit");
            return (Criteria) this;
        }

        public Criteria andCApprovalUnitGreaterThanOrEqualTo(String value) {
            addCriterion("c_approval_unit >=", value, "cApprovalUnit");
            return (Criteria) this;
        }

        public Criteria andCApprovalUnitLessThan(String value) {
            addCriterion("c_approval_unit <", value, "cApprovalUnit");
            return (Criteria) this;
        }

        public Criteria andCApprovalUnitLessThanOrEqualTo(String value) {
            addCriterion("c_approval_unit <=", value, "cApprovalUnit");
            return (Criteria) this;
        }

        public Criteria andCApprovalUnitLike(String value) {
            addCriterion("c_approval_unit like", value, "cApprovalUnit");
            return (Criteria) this;
        }

        public Criteria andCApprovalUnitNotLike(String value) {
            addCriterion("c_approval_unit not like", value, "cApprovalUnit");
            return (Criteria) this;
        }

        public Criteria andCApprovalUnitIn(List<String> values) {
            addCriterion("c_approval_unit in", values, "cApprovalUnit");
            return (Criteria) this;
        }

        public Criteria andCApprovalUnitNotIn(List<String> values) {
            addCriterion("c_approval_unit not in", values, "cApprovalUnit");
            return (Criteria) this;
        }

        public Criteria andCApprovalUnitBetween(String value1, String value2) {
            addCriterion("c_approval_unit between", value1, value2, "cApprovalUnit");
            return (Criteria) this;
        }

        public Criteria andCApprovalUnitNotBetween(String value1, String value2) {
            addCriterion("c_approval_unit not between", value1, value2, "cApprovalUnit");
            return (Criteria) this;
        }

        public Criteria andDApprovalDateIsNull() {
            addCriterion("d_approval_date is null");
            return (Criteria) this;
        }

        public Criteria andDApprovalDateIsNotNull() {
            addCriterion("d_approval_date is not null");
            return (Criteria) this;
        }

        public Criteria andDApprovalDateEqualTo(Date value) {
            addCriterionForJDBCDate("d_approval_date =", value, "dApprovalDate");
            return (Criteria) this;
        }

        public Criteria andDApprovalDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("d_approval_date <>", value, "dApprovalDate");
            return (Criteria) this;
        }

        public Criteria andDApprovalDateGreaterThan(Date value) {
            addCriterionForJDBCDate("d_approval_date >", value, "dApprovalDate");
            return (Criteria) this;
        }

        public Criteria andDApprovalDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("d_approval_date >=", value, "dApprovalDate");
            return (Criteria) this;
        }

        public Criteria andDApprovalDateLessThan(Date value) {
            addCriterionForJDBCDate("d_approval_date <", value, "dApprovalDate");
            return (Criteria) this;
        }

        public Criteria andDApprovalDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("d_approval_date <=", value, "dApprovalDate");
            return (Criteria) this;
        }

        public Criteria andDApprovalDateIn(List<Date> values) {
            addCriterionForJDBCDate("d_approval_date in", values, "dApprovalDate");
            return (Criteria) this;
        }

        public Criteria andDApprovalDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("d_approval_date not in", values, "dApprovalDate");
            return (Criteria) this;
        }

        public Criteria andDApprovalDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("d_approval_date between", value1, value2, "dApprovalDate");
            return (Criteria) this;
        }

        public Criteria andDApprovalDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("d_approval_date not between", value1, value2, "dApprovalDate");
            return (Criteria) this;
        }

        public Criteria andNIsFirstAppointJudgeIsNull() {
            addCriterion("n_is_first_appoint_judge is null");
            return (Criteria) this;
        }

        public Criteria andNIsFirstAppointJudgeIsNotNull() {
            addCriterion("n_is_first_appoint_judge is not null");
            return (Criteria) this;
        }

        public Criteria andNIsFirstAppointJudgeEqualTo(Integer value) {
            addCriterion("n_is_first_appoint_judge =", value, "nIsFirstAppointJudge");
            return (Criteria) this;
        }

        public Criteria andNIsFirstAppointJudgeNotEqualTo(Integer value) {
            addCriterion("n_is_first_appoint_judge <>", value, "nIsFirstAppointJudge");
            return (Criteria) this;
        }

        public Criteria andNIsFirstAppointJudgeGreaterThan(Integer value) {
            addCriterion("n_is_first_appoint_judge >", value, "nIsFirstAppointJudge");
            return (Criteria) this;
        }

        public Criteria andNIsFirstAppointJudgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("n_is_first_appoint_judge >=", value, "nIsFirstAppointJudge");
            return (Criteria) this;
        }

        public Criteria andNIsFirstAppointJudgeLessThan(Integer value) {
            addCriterion("n_is_first_appoint_judge <", value, "nIsFirstAppointJudge");
            return (Criteria) this;
        }

        public Criteria andNIsFirstAppointJudgeLessThanOrEqualTo(Integer value) {
            addCriterion("n_is_first_appoint_judge <=", value, "nIsFirstAppointJudge");
            return (Criteria) this;
        }

        public Criteria andNIsFirstAppointJudgeIn(List<Integer> values) {
            addCriterion("n_is_first_appoint_judge in", values, "nIsFirstAppointJudge");
            return (Criteria) this;
        }

        public Criteria andNIsFirstAppointJudgeNotIn(List<Integer> values) {
            addCriterion("n_is_first_appoint_judge not in", values, "nIsFirstAppointJudge");
            return (Criteria) this;
        }

        public Criteria andNIsFirstAppointJudgeBetween(Integer value1, Integer value2) {
            addCriterion("n_is_first_appoint_judge between", value1, value2, "nIsFirstAppointJudge");
            return (Criteria) this;
        }

        public Criteria andNIsFirstAppointJudgeNotBetween(Integer value1, Integer value2) {
            addCriterion("n_is_first_appoint_judge not between", value1, value2, "nIsFirstAppointJudge");
            return (Criteria) this;
        }

        public Criteria andNFirstJudgeYearIsNull() {
            addCriterion("n_first_judge_year is null");
            return (Criteria) this;
        }

        public Criteria andNFirstJudgeYearIsNotNull() {
            addCriterion("n_first_judge_year is not null");
            return (Criteria) this;
        }

        public Criteria andNFirstJudgeYearEqualTo(Integer value) {
            addCriterion("n_first_judge_year =", value, "nFirstJudgeYear");
            return (Criteria) this;
        }

        public Criteria andNFirstJudgeYearNotEqualTo(Integer value) {
            addCriterion("n_first_judge_year <>", value, "nFirstJudgeYear");
            return (Criteria) this;
        }

        public Criteria andNFirstJudgeYearGreaterThan(Integer value) {
            addCriterion("n_first_judge_year >", value, "nFirstJudgeYear");
            return (Criteria) this;
        }

        public Criteria andNFirstJudgeYearGreaterThanOrEqualTo(Integer value) {
            addCriterion("n_first_judge_year >=", value, "nFirstJudgeYear");
            return (Criteria) this;
        }

        public Criteria andNFirstJudgeYearLessThan(Integer value) {
            addCriterion("n_first_judge_year <", value, "nFirstJudgeYear");
            return (Criteria) this;
        }

        public Criteria andNFirstJudgeYearLessThanOrEqualTo(Integer value) {
            addCriterion("n_first_judge_year <=", value, "nFirstJudgeYear");
            return (Criteria) this;
        }

        public Criteria andNFirstJudgeYearIn(List<Integer> values) {
            addCriterion("n_first_judge_year in", values, "nFirstJudgeYear");
            return (Criteria) this;
        }

        public Criteria andNFirstJudgeYearNotIn(List<Integer> values) {
            addCriterion("n_first_judge_year not in", values, "nFirstJudgeYear");
            return (Criteria) this;
        }

        public Criteria andNFirstJudgeYearBetween(Integer value1, Integer value2) {
            addCriterion("n_first_judge_year between", value1, value2, "nFirstJudgeYear");
            return (Criteria) this;
        }

        public Criteria andNFirstJudgeYearNotBetween(Integer value1, Integer value2) {
            addCriterion("n_first_judge_year not between", value1, value2, "nFirstJudgeYear");
            return (Criteria) this;
        }

        public Criteria andNJobSituationIsNull() {
            addCriterion("n_job_situation is null");
            return (Criteria) this;
        }

        public Criteria andNJobSituationIsNotNull() {
            addCriterion("n_job_situation is not null");
            return (Criteria) this;
        }

        public Criteria andNJobSituationEqualTo(Integer value) {
            addCriterion("n_job_situation =", value, "nJobSituation");
            return (Criteria) this;
        }

        public Criteria andNJobSituationNotEqualTo(Integer value) {
            addCriterion("n_job_situation <>", value, "nJobSituation");
            return (Criteria) this;
        }

        public Criteria andNJobSituationGreaterThan(Integer value) {
            addCriterion("n_job_situation >", value, "nJobSituation");
            return (Criteria) this;
        }

        public Criteria andNJobSituationGreaterThanOrEqualTo(Integer value) {
            addCriterion("n_job_situation >=", value, "nJobSituation");
            return (Criteria) this;
        }

        public Criteria andNJobSituationLessThan(Integer value) {
            addCriterion("n_job_situation <", value, "nJobSituation");
            return (Criteria) this;
        }

        public Criteria andNJobSituationLessThanOrEqualTo(Integer value) {
            addCriterion("n_job_situation <=", value, "nJobSituation");
            return (Criteria) this;
        }

        public Criteria andNJobSituationIn(List<Integer> values) {
            addCriterion("n_job_situation in", values, "nJobSituation");
            return (Criteria) this;
        }

        public Criteria andNJobSituationNotIn(List<Integer> values) {
            addCriterion("n_job_situation not in", values, "nJobSituation");
            return (Criteria) this;
        }

        public Criteria andNJobSituationBetween(Integer value1, Integer value2) {
            addCriterion("n_job_situation between", value1, value2, "nJobSituation");
            return (Criteria) this;
        }

        public Criteria andNJobSituationNotBetween(Integer value1, Integer value2) {
            addCriterion("n_job_situation not between", value1, value2, "nJobSituation");
            return (Criteria) this;
        }

        public Criteria andNIsProIsNull() {
            addCriterion("n_is_pro is null");
            return (Criteria) this;
        }

        public Criteria andNIsProIsNotNull() {
            addCriterion("n_is_pro is not null");
            return (Criteria) this;
        }

        public Criteria andNIsProEqualTo(Integer value) {
            addCriterion("n_is_pro =", value, "nIsPro");
            return (Criteria) this;
        }

        public Criteria andNIsProNotEqualTo(Integer value) {
            addCriterion("n_is_pro <>", value, "nIsPro");
            return (Criteria) this;
        }

        public Criteria andNIsProGreaterThan(Integer value) {
            addCriterion("n_is_pro >", value, "nIsPro");
            return (Criteria) this;
        }

        public Criteria andNIsProGreaterThanOrEqualTo(Integer value) {
            addCriterion("n_is_pro >=", value, "nIsPro");
            return (Criteria) this;
        }

        public Criteria andNIsProLessThan(Integer value) {
            addCriterion("n_is_pro <", value, "nIsPro");
            return (Criteria) this;
        }

        public Criteria andNIsProLessThanOrEqualTo(Integer value) {
            addCriterion("n_is_pro <=", value, "nIsPro");
            return (Criteria) this;
        }

        public Criteria andNIsProIn(List<Integer> values) {
            addCriterion("n_is_pro in", values, "nIsPro");
            return (Criteria) this;
        }

        public Criteria andNIsProNotIn(List<Integer> values) {
            addCriterion("n_is_pro not in", values, "nIsPro");
            return (Criteria) this;
        }

        public Criteria andNIsProBetween(Integer value1, Integer value2) {
            addCriterion("n_is_pro between", value1, value2, "nIsPro");
            return (Criteria) this;
        }

        public Criteria andNIsProNotBetween(Integer value1, Integer value2) {
            addCriterion("n_is_pro not between", value1, value2, "nIsPro");
            return (Criteria) this;
        }

        public Criteria andNProSituationIsNull() {
            addCriterion("n_pro_situation is null");
            return (Criteria) this;
        }

        public Criteria andNProSituationIsNotNull() {
            addCriterion("n_pro_situation is not null");
            return (Criteria) this;
        }

        public Criteria andNProSituationEqualTo(Integer value) {
            addCriterion("n_pro_situation =", value, "nProSituation");
            return (Criteria) this;
        }

        public Criteria andNProSituationNotEqualTo(Integer value) {
            addCriterion("n_pro_situation <>", value, "nProSituation");
            return (Criteria) this;
        }

        public Criteria andNProSituationGreaterThan(Integer value) {
            addCriterion("n_pro_situation >", value, "nProSituation");
            return (Criteria) this;
        }

        public Criteria andNProSituationGreaterThanOrEqualTo(Integer value) {
            addCriterion("n_pro_situation >=", value, "nProSituation");
            return (Criteria) this;
        }

        public Criteria andNProSituationLessThan(Integer value) {
            addCriterion("n_pro_situation <", value, "nProSituation");
            return (Criteria) this;
        }

        public Criteria andNProSituationLessThanOrEqualTo(Integer value) {
            addCriterion("n_pro_situation <=", value, "nProSituation");
            return (Criteria) this;
        }

        public Criteria andNProSituationIn(List<Integer> values) {
            addCriterion("n_pro_situation in", values, "nProSituation");
            return (Criteria) this;
        }

        public Criteria andNProSituationNotIn(List<Integer> values) {
            addCriterion("n_pro_situation not in", values, "nProSituation");
            return (Criteria) this;
        }

        public Criteria andNProSituationBetween(Integer value1, Integer value2) {
            addCriterion("n_pro_situation between", value1, value2, "nProSituation");
            return (Criteria) this;
        }

        public Criteria andNProSituationNotBetween(Integer value1, Integer value2) {
            addCriterion("n_pro_situation not between", value1, value2, "nProSituation");
            return (Criteria) this;
        }

        public Criteria andRecordIdIsNull() {
            addCriterion("record_id is null");
            return (Criteria) this;
        }

        public Criteria andRecordIdIsNotNull() {
            addCriterion("record_id is not null");
            return (Criteria) this;
        }

        public Criteria andRecordIdEqualTo(String value) {
            addCriterion("record_id =", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotEqualTo(String value) {
            addCriterion("record_id <>", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdGreaterThan(String value) {
            addCriterion("record_id >", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdGreaterThanOrEqualTo(String value) {
            addCriterion("record_id >=", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdLessThan(String value) {
            addCriterion("record_id <", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdLessThanOrEqualTo(String value) {
            addCriterion("record_id <=", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdLike(String value) {
            addCriterion("record_id like", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotLike(String value) {
            addCriterion("record_id not like", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdIn(List<String> values) {
            addCriterion("record_id in", values, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotIn(List<String> values) {
            addCriterion("record_id not in", values, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdBetween(String value1, String value2) {
            addCriterion("record_id between", value1, value2, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotBetween(String value1, String value2) {
            addCriterion("record_id not between", value1, value2, "recordId");
            return (Criteria) this;
        }

        public Criteria andNPresentInfoIsNull() {
            addCriterion("n_present_info is null");
            return (Criteria) this;
        }

        public Criteria andNPresentInfoIsNotNull() {
            addCriterion("n_present_info is not null");
            return (Criteria) this;
        }

        public Criteria andNPresentInfoEqualTo(Integer value) {
            addCriterion("n_present_info =", value, "nPresentInfo");
            return (Criteria) this;
        }

        public Criteria andNPresentInfoNotEqualTo(Integer value) {
            addCriterion("n_present_info <>", value, "nPresentInfo");
            return (Criteria) this;
        }

        public Criteria andNPresentInfoGreaterThan(Integer value) {
            addCriterion("n_present_info >", value, "nPresentInfo");
            return (Criteria) this;
        }

        public Criteria andNPresentInfoGreaterThanOrEqualTo(Integer value) {
            addCriterion("n_present_info >=", value, "nPresentInfo");
            return (Criteria) this;
        }

        public Criteria andNPresentInfoLessThan(Integer value) {
            addCriterion("n_present_info <", value, "nPresentInfo");
            return (Criteria) this;
        }

        public Criteria andNPresentInfoLessThanOrEqualTo(Integer value) {
            addCriterion("n_present_info <=", value, "nPresentInfo");
            return (Criteria) this;
        }

        public Criteria andNPresentInfoIn(List<Integer> values) {
            addCriterion("n_present_info in", values, "nPresentInfo");
            return (Criteria) this;
        }

        public Criteria andNPresentInfoNotIn(List<Integer> values) {
            addCriterion("n_present_info not in", values, "nPresentInfo");
            return (Criteria) this;
        }

        public Criteria andNPresentInfoBetween(Integer value1, Integer value2) {
            addCriterion("n_present_info between", value1, value2, "nPresentInfo");
            return (Criteria) this;
        }

        public Criteria andNPresentInfoNotBetween(Integer value1, Integer value2) {
            addCriterion("n_present_info not between", value1, value2, "nPresentInfo");
            return (Criteria) this;
        }

        public Criteria andCourtCodeIsNull() {
            addCriterion("court_code is null");
            return (Criteria) this;
        }

        public Criteria andCourtCodeIsNotNull() {
            addCriterion("court_code is not null");
            return (Criteria) this;
        }

        public Criteria andCourtCodeEqualTo(String value) {
            addCriterion("court_code =", value, "courtCode");
            return (Criteria) this;
        }

        public Criteria andCourtCodeNotEqualTo(String value) {
            addCriterion("court_code <>", value, "courtCode");
            return (Criteria) this;
        }

        public Criteria andCourtCodeGreaterThan(String value) {
            addCriterion("court_code >", value, "courtCode");
            return (Criteria) this;
        }

        public Criteria andCourtCodeGreaterThanOrEqualTo(String value) {
            addCriterion("court_code >=", value, "courtCode");
            return (Criteria) this;
        }

        public Criteria andCourtCodeLessThan(String value) {
            addCriterion("court_code <", value, "courtCode");
            return (Criteria) this;
        }

        public Criteria andCourtCodeLessThanOrEqualTo(String value) {
            addCriterion("court_code <=", value, "courtCode");
            return (Criteria) this;
        }

        public Criteria andCourtCodeLike(String value) {
            addCriterion("court_code like", value, "courtCode");
            return (Criteria) this;
        }

        public Criteria andCourtCodeNotLike(String value) {
            addCriterion("court_code not like", value, "courtCode");
            return (Criteria) this;
        }

        public Criteria andCourtCodeIn(List<String> values) {
            addCriterion("court_code in", values, "courtCode");
            return (Criteria) this;
        }

        public Criteria andCourtCodeNotIn(List<String> values) {
            addCriterion("court_code not in", values, "courtCode");
            return (Criteria) this;
        }

        public Criteria andCourtCodeBetween(String value1, String value2) {
            addCriterion("court_code between", value1, value2, "courtCode");
            return (Criteria) this;
        }

        public Criteria andCourtCodeNotBetween(String value1, String value2) {
            addCriterion("court_code not between", value1, value2, "courtCode");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(String value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(String value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(String value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(String value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(String value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLike(String value) {
            addCriterion("update_time like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotLike(String value) {
            addCriterion("update_time not like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<String> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<String> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(String value1, String value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(String value1, String value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andNJobReportIsNull() {
            addCriterion("n_job_report is null");
            return (Criteria) this;
        }

        public Criteria andNJobReportIsNotNull() {
            addCriterion("n_job_report is not null");
            return (Criteria) this;
        }

        public Criteria andNJobReportEqualTo(String value) {
            addCriterion("n_job_report =", value, "nJobReport");
            return (Criteria) this;
        }

        public Criteria andNJobReportNotEqualTo(String value) {
            addCriterion("n_job_report <>", value, "nJobReport");
            return (Criteria) this;
        }

        public Criteria andNJobReportGreaterThan(String value) {
            addCriterion("n_job_report >", value, "nJobReport");
            return (Criteria) this;
        }

        public Criteria andNJobReportGreaterThanOrEqualTo(String value) {
            addCriterion("n_job_report >=", value, "nJobReport");
            return (Criteria) this;
        }

        public Criteria andNJobReportLessThan(String value) {
            addCriterion("n_job_report <", value, "nJobReport");
            return (Criteria) this;
        }

        public Criteria andNJobReportLessThanOrEqualTo(String value) {
            addCriterion("n_job_report <=", value, "nJobReport");
            return (Criteria) this;
        }

        public Criteria andNJobReportLike(String value) {
            addCriterion("n_job_report like", value, "nJobReport");
            return (Criteria) this;
        }

        public Criteria andNJobReportNotLike(String value) {
            addCriterion("n_job_report not like", value, "nJobReport");
            return (Criteria) this;
        }

        public Criteria andNJobReportIn(List<String> values) {
            addCriterion("n_job_report in", values, "nJobReport");
            return (Criteria) this;
        }

        public Criteria andNJobReportNotIn(List<String> values) {
            addCriterion("n_job_report not in", values, "nJobReport");
            return (Criteria) this;
        }

        public Criteria andNJobReportBetween(String value1, String value2) {
            addCriterion("n_job_report between", value1, value2, "nJobReport");
            return (Criteria) this;
        }

        public Criteria andNJobReportNotBetween(String value1, String value2) {
            addCriterion("n_job_report not between", value1, value2, "nJobReport");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ums_legal_job
     *
     * @mbggenerated do_not_delete_during_merge Fri Jun 08 16:34:01 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}