package cn.net.withub.ums.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class UmsProTechnicalPositionCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public UmsProTechnicalPositionCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andOldIdIsNull() {
            addCriterion("old_id is null");
            return (Criteria) this;
        }

        public Criteria andOldIdIsNotNull() {
            addCriterion("old_id is not null");
            return (Criteria) this;
        }

        public Criteria andOldIdEqualTo(Long value) {
            addCriterion("old_id =", value, "oldId");
            return (Criteria) this;
        }

        public Criteria andOldIdNotEqualTo(Long value) {
            addCriterion("old_id <>", value, "oldId");
            return (Criteria) this;
        }

        public Criteria andOldIdGreaterThan(Long value) {
            addCriterion("old_id >", value, "oldId");
            return (Criteria) this;
        }

        public Criteria andOldIdGreaterThanOrEqualTo(Long value) {
            addCriterion("old_id >=", value, "oldId");
            return (Criteria) this;
        }

        public Criteria andOldIdLessThan(Long value) {
            addCriterion("old_id <", value, "oldId");
            return (Criteria) this;
        }

        public Criteria andOldIdLessThanOrEqualTo(Long value) {
            addCriterion("old_id <=", value, "oldId");
            return (Criteria) this;
        }

        public Criteria andOldIdIn(List<Long> values) {
            addCriterion("old_id in", values, "oldId");
            return (Criteria) this;
        }

        public Criteria andOldIdNotIn(List<Long> values) {
            addCriterion("old_id not in", values, "oldId");
            return (Criteria) this;
        }

        public Criteria andOldIdBetween(Long value1, Long value2) {
            addCriterion("old_id between", value1, value2, "oldId");
            return (Criteria) this;
        }

        public Criteria andOldIdNotBetween(Long value1, Long value2) {
            addCriterion("old_id not between", value1, value2, "oldId");
            return (Criteria) this;
        }

        public Criteria andCourtNoIsNull() {
            addCriterion("court_no is null");
            return (Criteria) this;
        }

        public Criteria andCourtNoIsNotNull() {
            addCriterion("court_no is not null");
            return (Criteria) this;
        }

        public Criteria andCourtNoEqualTo(Integer value) {
            addCriterion("court_no =", value, "courtNo");
            return (Criteria) this;
        }

        public Criteria andCourtNoNotEqualTo(Integer value) {
            addCriterion("court_no <>", value, "courtNo");
            return (Criteria) this;
        }

        public Criteria andCourtNoGreaterThan(Integer value) {
            addCriterion("court_no >", value, "courtNo");
            return (Criteria) this;
        }

        public Criteria andCourtNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("court_no >=", value, "courtNo");
            return (Criteria) this;
        }

        public Criteria andCourtNoLessThan(Integer value) {
            addCriterion("court_no <", value, "courtNo");
            return (Criteria) this;
        }

        public Criteria andCourtNoLessThanOrEqualTo(Integer value) {
            addCriterion("court_no <=", value, "courtNo");
            return (Criteria) this;
        }

        public Criteria andCourtNoIn(List<Integer> values) {
            addCriterion("court_no in", values, "courtNo");
            return (Criteria) this;
        }

        public Criteria andCourtNoNotIn(List<Integer> values) {
            addCriterion("court_no not in", values, "courtNo");
            return (Criteria) this;
        }

        public Criteria andCourtNoBetween(Integer value1, Integer value2) {
            addCriterion("court_no between", value1, value2, "courtNo");
            return (Criteria) this;
        }

        public Criteria andCourtNoNotBetween(Integer value1, Integer value2) {
            addCriterion("court_no not between", value1, value2, "courtNo");
            return (Criteria) this;
        }

        public Criteria andUserNoIsNull() {
            addCriterion("user_no is null");
            return (Criteria) this;
        }

        public Criteria andUserNoIsNotNull() {
            addCriterion("user_no is not null");
            return (Criteria) this;
        }

        public Criteria andUserNoEqualTo(Integer value) {
            addCriterion("user_no =", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoNotEqualTo(Integer value) {
            addCriterion("user_no <>", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoGreaterThan(Integer value) {
            addCriterion("user_no >", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_no >=", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoLessThan(Integer value) {
            addCriterion("user_no <", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoLessThanOrEqualTo(Integer value) {
            addCriterion("user_no <=", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoIn(List<Integer> values) {
            addCriterion("user_no in", values, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoNotIn(List<Integer> values) {
            addCriterion("user_no not in", values, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoBetween(Integer value1, Integer value2) {
            addCriterion("user_no between", value1, value2, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoNotBetween(Integer value1, Integer value2) {
            addCriterion("user_no not between", value1, value2, "userNo");
            return (Criteria) this;
        }

        public Criteria andNPtNameIsNull() {
            addCriterion("n_pt_name is null");
            return (Criteria) this;
        }

        public Criteria andNPtNameIsNotNull() {
            addCriterion("n_pt_name is not null");
            return (Criteria) this;
        }

        public Criteria andNPtNameEqualTo(String value) {
            addCriterion("n_pt_name =", value, "nPtName");
            return (Criteria) this;
        }

        public Criteria andNPtNameNotEqualTo(String value) {
            addCriterion("n_pt_name <>", value, "nPtName");
            return (Criteria) this;
        }

        public Criteria andNPtNameGreaterThan(String value) {
            addCriterion("n_pt_name >", value, "nPtName");
            return (Criteria) this;
        }

        public Criteria andNPtNameGreaterThanOrEqualTo(String value) {
            addCriterion("n_pt_name >=", value, "nPtName");
            return (Criteria) this;
        }

        public Criteria andNPtNameLessThan(String value) {
            addCriterion("n_pt_name <", value, "nPtName");
            return (Criteria) this;
        }

        public Criteria andNPtNameLessThanOrEqualTo(String value) {
            addCriterion("n_pt_name <=", value, "nPtName");
            return (Criteria) this;
        }

        public Criteria andNPtNameLike(String value) {
            addCriterion("n_pt_name like", value, "nPtName");
            return (Criteria) this;
        }

        public Criteria andNPtNameNotLike(String value) {
            addCriterion("n_pt_name not like", value, "nPtName");
            return (Criteria) this;
        }

        public Criteria andNPtNameIn(List<String> values) {
            addCriterion("n_pt_name in", values, "nPtName");
            return (Criteria) this;
        }

        public Criteria andNPtNameNotIn(List<String> values) {
            addCriterion("n_pt_name not in", values, "nPtName");
            return (Criteria) this;
        }

        public Criteria andNPtNameBetween(String value1, String value2) {
            addCriterion("n_pt_name between", value1, value2, "nPtName");
            return (Criteria) this;
        }

        public Criteria andNPtNameNotBetween(String value1, String value2) {
            addCriterion("n_pt_name not between", value1, value2, "nPtName");
            return (Criteria) this;
        }

        public Criteria andNPtWayIsNull() {
            addCriterion("n_pt_way is null");
            return (Criteria) this;
        }

        public Criteria andNPtWayIsNotNull() {
            addCriterion("n_pt_way is not null");
            return (Criteria) this;
        }

        public Criteria andNPtWayEqualTo(String value) {
            addCriterion("n_pt_way =", value, "nPtWay");
            return (Criteria) this;
        }

        public Criteria andNPtWayNotEqualTo(String value) {
            addCriterion("n_pt_way <>", value, "nPtWay");
            return (Criteria) this;
        }

        public Criteria andNPtWayGreaterThan(String value) {
            addCriterion("n_pt_way >", value, "nPtWay");
            return (Criteria) this;
        }

        public Criteria andNPtWayGreaterThanOrEqualTo(String value) {
            addCriterion("n_pt_way >=", value, "nPtWay");
            return (Criteria) this;
        }

        public Criteria andNPtWayLessThan(String value) {
            addCriterion("n_pt_way <", value, "nPtWay");
            return (Criteria) this;
        }

        public Criteria andNPtWayLessThanOrEqualTo(String value) {
            addCriterion("n_pt_way <=", value, "nPtWay");
            return (Criteria) this;
        }

        public Criteria andNPtWayLike(String value) {
            addCriterion("n_pt_way like", value, "nPtWay");
            return (Criteria) this;
        }

        public Criteria andNPtWayNotLike(String value) {
            addCriterion("n_pt_way not like", value, "nPtWay");
            return (Criteria) this;
        }

        public Criteria andNPtWayIn(List<String> values) {
            addCriterion("n_pt_way in", values, "nPtWay");
            return (Criteria) this;
        }

        public Criteria andNPtWayNotIn(List<String> values) {
            addCriterion("n_pt_way not in", values, "nPtWay");
            return (Criteria) this;
        }

        public Criteria andNPtWayBetween(String value1, String value2) {
            addCriterion("n_pt_way between", value1, value2, "nPtWay");
            return (Criteria) this;
        }

        public Criteria andNPtWayNotBetween(String value1, String value2) {
            addCriterion("n_pt_way not between", value1, value2, "nPtWay");
            return (Criteria) this;
        }

        public Criteria andDPtDateIsNull() {
            addCriterion("d_pt_date is null");
            return (Criteria) this;
        }

        public Criteria andDPtDateIsNotNull() {
            addCriterion("d_pt_date is not null");
            return (Criteria) this;
        }

        public Criteria andDPtDateEqualTo(Date value) {
            addCriterionForJDBCDate("d_pt_date =", value, "dPtDate");
            return (Criteria) this;
        }

        public Criteria andDPtDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("d_pt_date <>", value, "dPtDate");
            return (Criteria) this;
        }

        public Criteria andDPtDateGreaterThan(Date value) {
            addCriterionForJDBCDate("d_pt_date >", value, "dPtDate");
            return (Criteria) this;
        }

        public Criteria andDPtDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("d_pt_date >=", value, "dPtDate");
            return (Criteria) this;
        }

        public Criteria andDPtDateLessThan(Date value) {
            addCriterionForJDBCDate("d_pt_date <", value, "dPtDate");
            return (Criteria) this;
        }

        public Criteria andDPtDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("d_pt_date <=", value, "dPtDate");
            return (Criteria) this;
        }

        public Criteria andDPtDateIn(List<Date> values) {
            addCriterionForJDBCDate("d_pt_date in", values, "dPtDate");
            return (Criteria) this;
        }

        public Criteria andDPtDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("d_pt_date not in", values, "dPtDate");
            return (Criteria) this;
        }

        public Criteria andDPtDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("d_pt_date between", value1, value2, "dPtDate");
            return (Criteria) this;
        }

        public Criteria andDPtDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("d_pt_date not between", value1, value2, "dPtDate");
            return (Criteria) this;
        }

        public Criteria andNEngageNameIsNull() {
            addCriterion("n_engage_name is null");
            return (Criteria) this;
        }

        public Criteria andNEngageNameIsNotNull() {
            addCriterion("n_engage_name is not null");
            return (Criteria) this;
        }

        public Criteria andNEngageNameEqualTo(String value) {
            addCriterion("n_engage_name =", value, "nEngageName");
            return (Criteria) this;
        }

        public Criteria andNEngageNameNotEqualTo(String value) {
            addCriterion("n_engage_name <>", value, "nEngageName");
            return (Criteria) this;
        }

        public Criteria andNEngageNameGreaterThan(String value) {
            addCriterion("n_engage_name >", value, "nEngageName");
            return (Criteria) this;
        }

        public Criteria andNEngageNameGreaterThanOrEqualTo(String value) {
            addCriterion("n_engage_name >=", value, "nEngageName");
            return (Criteria) this;
        }

        public Criteria andNEngageNameLessThan(String value) {
            addCriterion("n_engage_name <", value, "nEngageName");
            return (Criteria) this;
        }

        public Criteria andNEngageNameLessThanOrEqualTo(String value) {
            addCriterion("n_engage_name <=", value, "nEngageName");
            return (Criteria) this;
        }

        public Criteria andNEngageNameLike(String value) {
            addCriterion("n_engage_name like", value, "nEngageName");
            return (Criteria) this;
        }

        public Criteria andNEngageNameNotLike(String value) {
            addCriterion("n_engage_name not like", value, "nEngageName");
            return (Criteria) this;
        }

        public Criteria andNEngageNameIn(List<String> values) {
            addCriterion("n_engage_name in", values, "nEngageName");
            return (Criteria) this;
        }

        public Criteria andNEngageNameNotIn(List<String> values) {
            addCriterion("n_engage_name not in", values, "nEngageName");
            return (Criteria) this;
        }

        public Criteria andNEngageNameBetween(String value1, String value2) {
            addCriterion("n_engage_name between", value1, value2, "nEngageName");
            return (Criteria) this;
        }

        public Criteria andNEngageNameNotBetween(String value1, String value2) {
            addCriterion("n_engage_name not between", value1, value2, "nEngageName");
            return (Criteria) this;
        }

        public Criteria andDEngageDateIsNull() {
            addCriterion("d_engage_date is null");
            return (Criteria) this;
        }

        public Criteria andDEngageDateIsNotNull() {
            addCriterion("d_engage_date is not null");
            return (Criteria) this;
        }

        public Criteria andDEngageDateEqualTo(Date value) {
            addCriterionForJDBCDate("d_engage_date =", value, "dEngageDate");
            return (Criteria) this;
        }

        public Criteria andDEngageDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("d_engage_date <>", value, "dEngageDate");
            return (Criteria) this;
        }

        public Criteria andDEngageDateGreaterThan(Date value) {
            addCriterionForJDBCDate("d_engage_date >", value, "dEngageDate");
            return (Criteria) this;
        }

        public Criteria andDEngageDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("d_engage_date >=", value, "dEngageDate");
            return (Criteria) this;
        }

        public Criteria andDEngageDateLessThan(Date value) {
            addCriterionForJDBCDate("d_engage_date <", value, "dEngageDate");
            return (Criteria) this;
        }

        public Criteria andDEngageDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("d_engage_date <=", value, "dEngageDate");
            return (Criteria) this;
        }

        public Criteria andDEngageDateIn(List<Date> values) {
            addCriterionForJDBCDate("d_engage_date in", values, "dEngageDate");
            return (Criteria) this;
        }

        public Criteria andDEngageDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("d_engage_date not in", values, "dEngageDate");
            return (Criteria) this;
        }

        public Criteria andDEngageDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("d_engage_date between", value1, value2, "dEngageDate");
            return (Criteria) this;
        }

        public Criteria andDEngageDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("d_engage_date not between", value1, value2, "dEngageDate");
            return (Criteria) this;
        }

        public Criteria andNTitleRankIsNull() {
            addCriterion("n_title_rank is null");
            return (Criteria) this;
        }

        public Criteria andNTitleRankIsNotNull() {
            addCriterion("n_title_rank is not null");
            return (Criteria) this;
        }

        public Criteria andNTitleRankEqualTo(String value) {
            addCriterion("n_title_rank =", value, "nTitleRank");
            return (Criteria) this;
        }

        public Criteria andNTitleRankNotEqualTo(String value) {
            addCriterion("n_title_rank <>", value, "nTitleRank");
            return (Criteria) this;
        }

        public Criteria andNTitleRankGreaterThan(String value) {
            addCriterion("n_title_rank >", value, "nTitleRank");
            return (Criteria) this;
        }

        public Criteria andNTitleRankGreaterThanOrEqualTo(String value) {
            addCriterion("n_title_rank >=", value, "nTitleRank");
            return (Criteria) this;
        }

        public Criteria andNTitleRankLessThan(String value) {
            addCriterion("n_title_rank <", value, "nTitleRank");
            return (Criteria) this;
        }

        public Criteria andNTitleRankLessThanOrEqualTo(String value) {
            addCriterion("n_title_rank <=", value, "nTitleRank");
            return (Criteria) this;
        }

        public Criteria andNTitleRankLike(String value) {
            addCriterion("n_title_rank like", value, "nTitleRank");
            return (Criteria) this;
        }

        public Criteria andNTitleRankNotLike(String value) {
            addCriterion("n_title_rank not like", value, "nTitleRank");
            return (Criteria) this;
        }

        public Criteria andNTitleRankIn(List<String> values) {
            addCriterion("n_title_rank in", values, "nTitleRank");
            return (Criteria) this;
        }

        public Criteria andNTitleRankNotIn(List<String> values) {
            addCriterion("n_title_rank not in", values, "nTitleRank");
            return (Criteria) this;
        }

        public Criteria andNTitleRankBetween(String value1, String value2) {
            addCriterion("n_title_rank between", value1, value2, "nTitleRank");
            return (Criteria) this;
        }

        public Criteria andNTitleRankNotBetween(String value1, String value2) {
            addCriterion("n_title_rank not between", value1, value2, "nTitleRank");
            return (Criteria) this;
        }

        public Criteria andSortNoIsNull() {
            addCriterion("sort_no is null");
            return (Criteria) this;
        }

        public Criteria andSortNoIsNotNull() {
            addCriterion("sort_no is not null");
            return (Criteria) this;
        }

        public Criteria andSortNoEqualTo(Integer value) {
            addCriterion("sort_no =", value, "sortNo");
            return (Criteria) this;
        }

        public Criteria andSortNoNotEqualTo(Integer value) {
            addCriterion("sort_no <>", value, "sortNo");
            return (Criteria) this;
        }

        public Criteria andSortNoGreaterThan(Integer value) {
            addCriterion("sort_no >", value, "sortNo");
            return (Criteria) this;
        }

        public Criteria andSortNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("sort_no >=", value, "sortNo");
            return (Criteria) this;
        }

        public Criteria andSortNoLessThan(Integer value) {
            addCriterion("sort_no <", value, "sortNo");
            return (Criteria) this;
        }

        public Criteria andSortNoLessThanOrEqualTo(Integer value) {
            addCriterion("sort_no <=", value, "sortNo");
            return (Criteria) this;
        }

        public Criteria andSortNoIn(List<Integer> values) {
            addCriterion("sort_no in", values, "sortNo");
            return (Criteria) this;
        }

        public Criteria andSortNoNotIn(List<Integer> values) {
            addCriterion("sort_no not in", values, "sortNo");
            return (Criteria) this;
        }

        public Criteria andSortNoBetween(Integer value1, Integer value2) {
            addCriterion("sort_no between", value1, value2, "sortNo");
            return (Criteria) this;
        }

        public Criteria andSortNoNotBetween(Integer value1, Integer value2) {
            addCriterion("sort_no not between", value1, value2, "sortNo");
            return (Criteria) this;
        }

        public Criteria andNIsVerifiedIsNull() {
            addCriterion("n_is_verified is null");
            return (Criteria) this;
        }

        public Criteria andNIsVerifiedIsNotNull() {
            addCriterion("n_is_verified is not null");
            return (Criteria) this;
        }

        public Criteria andNIsVerifiedEqualTo(Integer value) {
            addCriterion("n_is_verified =", value, "nIsVerified");
            return (Criteria) this;
        }

        public Criteria andNIsVerifiedNotEqualTo(Integer value) {
            addCriterion("n_is_verified <>", value, "nIsVerified");
            return (Criteria) this;
        }

        public Criteria andNIsVerifiedGreaterThan(Integer value) {
            addCriterion("n_is_verified >", value, "nIsVerified");
            return (Criteria) this;
        }

        public Criteria andNIsVerifiedGreaterThanOrEqualTo(Integer value) {
            addCriterion("n_is_verified >=", value, "nIsVerified");
            return (Criteria) this;
        }

        public Criteria andNIsVerifiedLessThan(Integer value) {
            addCriterion("n_is_verified <", value, "nIsVerified");
            return (Criteria) this;
        }

        public Criteria andNIsVerifiedLessThanOrEqualTo(Integer value) {
            addCriterion("n_is_verified <=", value, "nIsVerified");
            return (Criteria) this;
        }

        public Criteria andNIsVerifiedIn(List<Integer> values) {
            addCriterion("n_is_verified in", values, "nIsVerified");
            return (Criteria) this;
        }

        public Criteria andNIsVerifiedNotIn(List<Integer> values) {
            addCriterion("n_is_verified not in", values, "nIsVerified");
            return (Criteria) this;
        }

        public Criteria andNIsVerifiedBetween(Integer value1, Integer value2) {
            addCriterion("n_is_verified between", value1, value2, "nIsVerified");
            return (Criteria) this;
        }

        public Criteria andNIsVerifiedNotBetween(Integer value1, Integer value2) {
            addCriterion("n_is_verified not between", value1, value2, "nIsVerified");
            return (Criteria) this;
        }

        public Criteria andCourtCodeIsNull() {
            addCriterion("court_code is null");
            return (Criteria) this;
        }

        public Criteria andCourtCodeIsNotNull() {
            addCriterion("court_code is not null");
            return (Criteria) this;
        }

        public Criteria andCourtCodeEqualTo(String value) {
            addCriterion("court_code =", value, "courtCode");
            return (Criteria) this;
        }

        public Criteria andCourtCodeNotEqualTo(String value) {
            addCriterion("court_code <>", value, "courtCode");
            return (Criteria) this;
        }

        public Criteria andCourtCodeGreaterThan(String value) {
            addCriterion("court_code >", value, "courtCode");
            return (Criteria) this;
        }

        public Criteria andCourtCodeGreaterThanOrEqualTo(String value) {
            addCriterion("court_code >=", value, "courtCode");
            return (Criteria) this;
        }

        public Criteria andCourtCodeLessThan(String value) {
            addCriterion("court_code <", value, "courtCode");
            return (Criteria) this;
        }

        public Criteria andCourtCodeLessThanOrEqualTo(String value) {
            addCriterion("court_code <=", value, "courtCode");
            return (Criteria) this;
        }

        public Criteria andCourtCodeLike(String value) {
            addCriterion("court_code like", value, "courtCode");
            return (Criteria) this;
        }

        public Criteria andCourtCodeNotLike(String value) {
            addCriterion("court_code not like", value, "courtCode");
            return (Criteria) this;
        }

        public Criteria andCourtCodeIn(List<String> values) {
            addCriterion("court_code in", values, "courtCode");
            return (Criteria) this;
        }

        public Criteria andCourtCodeNotIn(List<String> values) {
            addCriterion("court_code not in", values, "courtCode");
            return (Criteria) this;
        }

        public Criteria andCourtCodeBetween(String value1, String value2) {
            addCriterion("court_code between", value1, value2, "courtCode");
            return (Criteria) this;
        }

        public Criteria andCourtCodeNotBetween(String value1, String value2) {
            addCriterion("court_code not between", value1, value2, "courtCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated do_not_delete_during_merge Wed May 16 17:25:15 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}