package cn.net.withub.ums.entity;

import java.util.Date;

public class UmsProTechnicalPosition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_pro_technical_position.id
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_pro_technical_position.user_id
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_pro_technical_position.old_id
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private Long oldId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_pro_technical_position.court_no
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private Integer courtNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_pro_technical_position.user_no
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private Integer userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_pro_technical_position.n_pt_name
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private String nPtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_pro_technical_position.n_pt_way
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private String nPtWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_pro_technical_position.d_pt_date
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private Date dPtDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_pro_technical_position.n_engage_name
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private String nEngageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_pro_technical_position.d_engage_date
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private Date dEngageDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_pro_technical_position.n_title_rank
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private String nTitleRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_pro_technical_position.sort_no
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private Integer sortNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_pro_technical_position.n_is_verified
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private Integer nIsVerified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_pro_technical_position.court_code
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    private String courtCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_pro_technical_position.id
     *
     * @return the value of ums_pro_technical_position.id
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_pro_technical_position.id
     *
     * @param id the value for ums_pro_technical_position.id
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_pro_technical_position.user_id
     *
     * @return the value of ums_pro_technical_position.user_id
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_pro_technical_position.user_id
     *
     * @param userId the value for ums_pro_technical_position.user_id
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_pro_technical_position.old_id
     *
     * @return the value of ums_pro_technical_position.old_id
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public Long getOldId() {
        return oldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_pro_technical_position.old_id
     *
     * @param oldId the value for ums_pro_technical_position.old_id
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setOldId(Long oldId) {
        this.oldId = oldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_pro_technical_position.court_no
     *
     * @return the value of ums_pro_technical_position.court_no
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public Integer getCourtNo() {
        return courtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_pro_technical_position.court_no
     *
     * @param courtNo the value for ums_pro_technical_position.court_no
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setCourtNo(Integer courtNo) {
        this.courtNo = courtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_pro_technical_position.user_no
     *
     * @return the value of ums_pro_technical_position.user_no
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public Integer getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_pro_technical_position.user_no
     *
     * @param userNo the value for ums_pro_technical_position.user_no
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setUserNo(Integer userNo) {
        this.userNo = userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_pro_technical_position.n_pt_name
     *
     * @return the value of ums_pro_technical_position.n_pt_name
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public String getnPtName() {
        return nPtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_pro_technical_position.n_pt_name
     *
     * @param nPtName the value for ums_pro_technical_position.n_pt_name
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setnPtName(String nPtName) {
        this.nPtName = nPtName == null ? null : nPtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_pro_technical_position.n_pt_way
     *
     * @return the value of ums_pro_technical_position.n_pt_way
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public String getnPtWay() {
        return nPtWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_pro_technical_position.n_pt_way
     *
     * @param nPtWay the value for ums_pro_technical_position.n_pt_way
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setnPtWay(String nPtWay) {
        this.nPtWay = nPtWay == null ? null : nPtWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_pro_technical_position.d_pt_date
     *
     * @return the value of ums_pro_technical_position.d_pt_date
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public Date getdPtDate() {
        return dPtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_pro_technical_position.d_pt_date
     *
     * @param dPtDate the value for ums_pro_technical_position.d_pt_date
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setdPtDate(Date dPtDate) {
        this.dPtDate = dPtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_pro_technical_position.n_engage_name
     *
     * @return the value of ums_pro_technical_position.n_engage_name
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public String getnEngageName() {
        return nEngageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_pro_technical_position.n_engage_name
     *
     * @param nEngageName the value for ums_pro_technical_position.n_engage_name
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setnEngageName(String nEngageName) {
        this.nEngageName = nEngageName == null ? null : nEngageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_pro_technical_position.d_engage_date
     *
     * @return the value of ums_pro_technical_position.d_engage_date
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public Date getdEngageDate() {
        return dEngageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_pro_technical_position.d_engage_date
     *
     * @param dEngageDate the value for ums_pro_technical_position.d_engage_date
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setdEngageDate(Date dEngageDate) {
        this.dEngageDate = dEngageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_pro_technical_position.n_title_rank
     *
     * @return the value of ums_pro_technical_position.n_title_rank
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public String getnTitleRank() {
        return nTitleRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_pro_technical_position.n_title_rank
     *
     * @param nTitleRank the value for ums_pro_technical_position.n_title_rank
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setnTitleRank(String nTitleRank) {
        this.nTitleRank = nTitleRank == null ? null : nTitleRank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_pro_technical_position.sort_no
     *
     * @return the value of ums_pro_technical_position.sort_no
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public Integer getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_pro_technical_position.sort_no
     *
     * @param sortNo the value for ums_pro_technical_position.sort_no
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setSortNo(Integer sortNo) {
        this.sortNo = sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_pro_technical_position.n_is_verified
     *
     * @return the value of ums_pro_technical_position.n_is_verified
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public Integer getnIsVerified() {
        return nIsVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_pro_technical_position.n_is_verified
     *
     * @param nIsVerified the value for ums_pro_technical_position.n_is_verified
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setnIsVerified(Integer nIsVerified) {
        this.nIsVerified = nIsVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_pro_technical_position.court_code
     *
     * @return the value of ums_pro_technical_position.court_code
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public String getCourtCode() {
        return courtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_pro_technical_position.court_code
     *
     * @param courtCode the value for ums_pro_technical_position.court_code
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    public void setCourtCode(String courtCode) {
        this.courtCode = courtCode == null ? null : courtCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UmsProTechnicalPosition other = (UmsProTechnicalPosition) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getOldId() == null ? other.getOldId() == null : this.getOldId().equals(other.getOldId()))
            && (this.getCourtNo() == null ? other.getCourtNo() == null : this.getCourtNo().equals(other.getCourtNo()))
            && (this.getUserNo() == null ? other.getUserNo() == null : this.getUserNo().equals(other.getUserNo()))
            && (this.getnPtName() == null ? other.getnPtName() == null : this.getnPtName().equals(other.getnPtName()))
            && (this.getnPtWay() == null ? other.getnPtWay() == null : this.getnPtWay().equals(other.getnPtWay()))
            && (this.getdPtDate() == null ? other.getdPtDate() == null : this.getdPtDate().equals(other.getdPtDate()))
            && (this.getnEngageName() == null ? other.getnEngageName() == null : this.getnEngageName().equals(other.getnEngageName()))
            && (this.getdEngageDate() == null ? other.getdEngageDate() == null : this.getdEngageDate().equals(other.getdEngageDate()))
            && (this.getnTitleRank() == null ? other.getnTitleRank() == null : this.getnTitleRank().equals(other.getnTitleRank()))
            && (this.getSortNo() == null ? other.getSortNo() == null : this.getSortNo().equals(other.getSortNo()))
            && (this.getnIsVerified() == null ? other.getnIsVerified() == null : this.getnIsVerified().equals(other.getnIsVerified()))
            && (this.getCourtCode() == null ? other.getCourtCode() == null : this.getCourtCode().equals(other.getCourtCode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:25:15 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getOldId() == null) ? 0 : getOldId().hashCode());
        result = prime * result + ((getCourtNo() == null) ? 0 : getCourtNo().hashCode());
        result = prime * result + ((getUserNo() == null) ? 0 : getUserNo().hashCode());
        result = prime * result + ((getnPtName() == null) ? 0 : getnPtName().hashCode());
        result = prime * result + ((getnPtWay() == null) ? 0 : getnPtWay().hashCode());
        result = prime * result + ((getdPtDate() == null) ? 0 : getdPtDate().hashCode());
        result = prime * result + ((getnEngageName() == null) ? 0 : getnEngageName().hashCode());
        result = prime * result + ((getdEngageDate() == null) ? 0 : getdEngageDate().hashCode());
        result = prime * result + ((getnTitleRank() == null) ? 0 : getnTitleRank().hashCode());
        result = prime * result + ((getSortNo() == null) ? 0 : getSortNo().hashCode());
        result = prime * result + ((getnIsVerified() == null) ? 0 : getnIsVerified().hashCode());
        result = prime * result + ((getCourtCode() == null) ? 0 : getCourtCode().hashCode());
        return result;
    }
}