package cn.net.withub.ums.entity;

import java.util.Date;

public class UmsRankInfoView {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.id
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.user_id
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.sort_no
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private Integer sortNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.old_id
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private Long oldId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.court_no
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private Integer courtNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.user_no
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private Integer userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.n_assign_type
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private Integer nAssignType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.n_rank
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private String nRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.n_rank_nature
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private String nRankNature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.c_unit
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private String cUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.c_department
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private String cDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.d_assign_date
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private Date dAssignDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.n_assign_reason
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private Integer nAssignReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.c_approval_unit
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private String cApprovalUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.c_approval_doc_no
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private String cApprovalDocNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.d_approval_date
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private Date dApprovalDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.record_id
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private String recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.n_present_info
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private Integer nPresentInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.court_code
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private String courtCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.update_time
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.n_rank_report
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private String nRankReport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.court_no_text
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private String courtNoText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.n_assign_type_text
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private String nAssignTypeText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.n_rank_text
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private String nRankText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.n_rank_nature_text
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private String nRankNatureText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.n_assign_reason_text
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private String nAssignReasonText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.n_present_info_text
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private String nPresentInfoText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_rank_info_view.n_rank_report_text
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    private String nRankReportText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.id
     *
     * @return the value of ums_rank_info_view.id
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.id
     *
     * @param id the value for ums_rank_info_view.id
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.user_id
     *
     * @return the value of ums_rank_info_view.user_id
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.user_id
     *
     * @param userId the value for ums_rank_info_view.user_id
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.sort_no
     *
     * @return the value of ums_rank_info_view.sort_no
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public Integer getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.sort_no
     *
     * @param sortNo the value for ums_rank_info_view.sort_no
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setSortNo(Integer sortNo) {
        this.sortNo = sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.old_id
     *
     * @return the value of ums_rank_info_view.old_id
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public Long getOldId() {
        return oldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.old_id
     *
     * @param oldId the value for ums_rank_info_view.old_id
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setOldId(Long oldId) {
        this.oldId = oldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.court_no
     *
     * @return the value of ums_rank_info_view.court_no
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public Integer getCourtNo() {
        return courtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.court_no
     *
     * @param courtNo the value for ums_rank_info_view.court_no
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setCourtNo(Integer courtNo) {
        this.courtNo = courtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.user_no
     *
     * @return the value of ums_rank_info_view.user_no
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public Integer getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.user_no
     *
     * @param userNo the value for ums_rank_info_view.user_no
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setUserNo(Integer userNo) {
        this.userNo = userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.n_assign_type
     *
     * @return the value of ums_rank_info_view.n_assign_type
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public Integer getnAssignType() {
        return nAssignType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.n_assign_type
     *
     * @param nAssignType the value for ums_rank_info_view.n_assign_type
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setnAssignType(Integer nAssignType) {
        this.nAssignType = nAssignType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.n_rank
     *
     * @return the value of ums_rank_info_view.n_rank
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public String getnRank() {
        return nRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.n_rank
     *
     * @param nRank the value for ums_rank_info_view.n_rank
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setnRank(String nRank) {
        this.nRank = nRank == null ? null : nRank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.n_rank_nature
     *
     * @return the value of ums_rank_info_view.n_rank_nature
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public String getnRankNature() {
        return nRankNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.n_rank_nature
     *
     * @param nRankNature the value for ums_rank_info_view.n_rank_nature
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setnRankNature(String nRankNature) {
        this.nRankNature = nRankNature == null ? null : nRankNature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.c_unit
     *
     * @return the value of ums_rank_info_view.c_unit
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public String getcUnit() {
        return cUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.c_unit
     *
     * @param cUnit the value for ums_rank_info_view.c_unit
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setcUnit(String cUnit) {
        this.cUnit = cUnit == null ? null : cUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.c_department
     *
     * @return the value of ums_rank_info_view.c_department
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public String getcDepartment() {
        return cDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.c_department
     *
     * @param cDepartment the value for ums_rank_info_view.c_department
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setcDepartment(String cDepartment) {
        this.cDepartment = cDepartment == null ? null : cDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.d_assign_date
     *
     * @return the value of ums_rank_info_view.d_assign_date
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public Date getdAssignDate() {
        return dAssignDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.d_assign_date
     *
     * @param dAssignDate the value for ums_rank_info_view.d_assign_date
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setdAssignDate(Date dAssignDate) {
        this.dAssignDate = dAssignDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.n_assign_reason
     *
     * @return the value of ums_rank_info_view.n_assign_reason
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public Integer getnAssignReason() {
        return nAssignReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.n_assign_reason
     *
     * @param nAssignReason the value for ums_rank_info_view.n_assign_reason
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setnAssignReason(Integer nAssignReason) {
        this.nAssignReason = nAssignReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.c_approval_unit
     *
     * @return the value of ums_rank_info_view.c_approval_unit
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public String getcApprovalUnit() {
        return cApprovalUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.c_approval_unit
     *
     * @param cApprovalUnit the value for ums_rank_info_view.c_approval_unit
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setcApprovalUnit(String cApprovalUnit) {
        this.cApprovalUnit = cApprovalUnit == null ? null : cApprovalUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.c_approval_doc_no
     *
     * @return the value of ums_rank_info_view.c_approval_doc_no
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public String getcApprovalDocNo() {
        return cApprovalDocNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.c_approval_doc_no
     *
     * @param cApprovalDocNo the value for ums_rank_info_view.c_approval_doc_no
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setcApprovalDocNo(String cApprovalDocNo) {
        this.cApprovalDocNo = cApprovalDocNo == null ? null : cApprovalDocNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.d_approval_date
     *
     * @return the value of ums_rank_info_view.d_approval_date
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public Date getdApprovalDate() {
        return dApprovalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.d_approval_date
     *
     * @param dApprovalDate the value for ums_rank_info_view.d_approval_date
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setdApprovalDate(Date dApprovalDate) {
        this.dApprovalDate = dApprovalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.record_id
     *
     * @return the value of ums_rank_info_view.record_id
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.record_id
     *
     * @param recordId the value for ums_rank_info_view.record_id
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId == null ? null : recordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.n_present_info
     *
     * @return the value of ums_rank_info_view.n_present_info
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public Integer getnPresentInfo() {
        return nPresentInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.n_present_info
     *
     * @param nPresentInfo the value for ums_rank_info_view.n_present_info
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setnPresentInfo(Integer nPresentInfo) {
        this.nPresentInfo = nPresentInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.court_code
     *
     * @return the value of ums_rank_info_view.court_code
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public String getCourtCode() {
        return courtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.court_code
     *
     * @param courtCode the value for ums_rank_info_view.court_code
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setCourtCode(String courtCode) {
        this.courtCode = courtCode == null ? null : courtCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.update_time
     *
     * @return the value of ums_rank_info_view.update_time
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.update_time
     *
     * @param updateTime the value for ums_rank_info_view.update_time
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.n_rank_report
     *
     * @return the value of ums_rank_info_view.n_rank_report
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public String getnRankReport() {
        return nRankReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.n_rank_report
     *
     * @param nRankReport the value for ums_rank_info_view.n_rank_report
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setnRankReport(String nRankReport) {
        this.nRankReport = nRankReport == null ? null : nRankReport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.court_no_text
     *
     * @return the value of ums_rank_info_view.court_no_text
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public String getCourtNoText() {
        return courtNoText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.court_no_text
     *
     * @param courtNoText the value for ums_rank_info_view.court_no_text
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setCourtNoText(String courtNoText) {
        this.courtNoText = courtNoText == null ? null : courtNoText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.n_assign_type_text
     *
     * @return the value of ums_rank_info_view.n_assign_type_text
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public String getnAssignTypeText() {
        return nAssignTypeText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.n_assign_type_text
     *
     * @param nAssignTypeText the value for ums_rank_info_view.n_assign_type_text
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setnAssignTypeText(String nAssignTypeText) {
        this.nAssignTypeText = nAssignTypeText == null ? null : nAssignTypeText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.n_rank_text
     *
     * @return the value of ums_rank_info_view.n_rank_text
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public String getnRankText() {
        return nRankText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.n_rank_text
     *
     * @param nRankText the value for ums_rank_info_view.n_rank_text
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setnRankText(String nRankText) {
        this.nRankText = nRankText == null ? null : nRankText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.n_rank_nature_text
     *
     * @return the value of ums_rank_info_view.n_rank_nature_text
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public String getnRankNatureText() {
        return nRankNatureText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.n_rank_nature_text
     *
     * @param nRankNatureText the value for ums_rank_info_view.n_rank_nature_text
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setnRankNatureText(String nRankNatureText) {
        this.nRankNatureText = nRankNatureText == null ? null : nRankNatureText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.n_assign_reason_text
     *
     * @return the value of ums_rank_info_view.n_assign_reason_text
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public String getnAssignReasonText() {
        return nAssignReasonText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.n_assign_reason_text
     *
     * @param nAssignReasonText the value for ums_rank_info_view.n_assign_reason_text
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setnAssignReasonText(String nAssignReasonText) {
        this.nAssignReasonText = nAssignReasonText == null ? null : nAssignReasonText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.n_present_info_text
     *
     * @return the value of ums_rank_info_view.n_present_info_text
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public String getnPresentInfoText() {
        return nPresentInfoText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.n_present_info_text
     *
     * @param nPresentInfoText the value for ums_rank_info_view.n_present_info_text
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setnPresentInfoText(String nPresentInfoText) {
        this.nPresentInfoText = nPresentInfoText == null ? null : nPresentInfoText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_rank_info_view.n_rank_report_text
     *
     * @return the value of ums_rank_info_view.n_rank_report_text
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public String getnRankReportText() {
        return nRankReportText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_rank_info_view.n_rank_report_text
     *
     * @param nRankReportText the value for ums_rank_info_view.n_rank_report_text
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    public void setnRankReportText(String nRankReportText) {
        this.nRankReportText = nRankReportText == null ? null : nRankReportText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_rank_info_view
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UmsRankInfoView other = (UmsRankInfoView) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getSortNo() == null ? other.getSortNo() == null : this.getSortNo().equals(other.getSortNo()))
            && (this.getOldId() == null ? other.getOldId() == null : this.getOldId().equals(other.getOldId()))
            && (this.getCourtNo() == null ? other.getCourtNo() == null : this.getCourtNo().equals(other.getCourtNo()))
            && (this.getUserNo() == null ? other.getUserNo() == null : this.getUserNo().equals(other.getUserNo()))
            && (this.getnAssignType() == null ? other.getnAssignType() == null : this.getnAssignType().equals(other.getnAssignType()))
            && (this.getnRank() == null ? other.getnRank() == null : this.getnRank().equals(other.getnRank()))
            && (this.getnRankNature() == null ? other.getnRankNature() == null : this.getnRankNature().equals(other.getnRankNature()))
            && (this.getcUnit() == null ? other.getcUnit() == null : this.getcUnit().equals(other.getcUnit()))
            && (this.getcDepartment() == null ? other.getcDepartment() == null : this.getcDepartment().equals(other.getcDepartment()))
            && (this.getdAssignDate() == null ? other.getdAssignDate() == null : this.getdAssignDate().equals(other.getdAssignDate()))
            && (this.getnAssignReason() == null ? other.getnAssignReason() == null : this.getnAssignReason().equals(other.getnAssignReason()))
            && (this.getcApprovalUnit() == null ? other.getcApprovalUnit() == null : this.getcApprovalUnit().equals(other.getcApprovalUnit()))
            && (this.getcApprovalDocNo() == null ? other.getcApprovalDocNo() == null : this.getcApprovalDocNo().equals(other.getcApprovalDocNo()))
            && (this.getdApprovalDate() == null ? other.getdApprovalDate() == null : this.getdApprovalDate().equals(other.getdApprovalDate()))
            && (this.getRecordId() == null ? other.getRecordId() == null : this.getRecordId().equals(other.getRecordId()))
            && (this.getnPresentInfo() == null ? other.getnPresentInfo() == null : this.getnPresentInfo().equals(other.getnPresentInfo()))
            && (this.getCourtCode() == null ? other.getCourtCode() == null : this.getCourtCode().equals(other.getCourtCode()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getnRankReport() == null ? other.getnRankReport() == null : this.getnRankReport().equals(other.getnRankReport()))
            && (this.getCourtNoText() == null ? other.getCourtNoText() == null : this.getCourtNoText().equals(other.getCourtNoText()))
            && (this.getnAssignTypeText() == null ? other.getnAssignTypeText() == null : this.getnAssignTypeText().equals(other.getnAssignTypeText()))
            && (this.getnRankText() == null ? other.getnRankText() == null : this.getnRankText().equals(other.getnRankText()))
            && (this.getnRankNatureText() == null ? other.getnRankNatureText() == null : this.getnRankNatureText().equals(other.getnRankNatureText()))
            && (this.getnAssignReasonText() == null ? other.getnAssignReasonText() == null : this.getnAssignReasonText().equals(other.getnAssignReasonText()))
            && (this.getnPresentInfoText() == null ? other.getnPresentInfoText() == null : this.getnPresentInfoText().equals(other.getnPresentInfoText()))
            && (this.getnRankReportText() == null ? other.getnRankReportText() == null : this.getnRankReportText().equals(other.getnRankReportText()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_rank_info_view
     *
     * @mbggenerated Fri Jun 08 16:34:01 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getSortNo() == null) ? 0 : getSortNo().hashCode());
        result = prime * result + ((getOldId() == null) ? 0 : getOldId().hashCode());
        result = prime * result + ((getCourtNo() == null) ? 0 : getCourtNo().hashCode());
        result = prime * result + ((getUserNo() == null) ? 0 : getUserNo().hashCode());
        result = prime * result + ((getnAssignType() == null) ? 0 : getnAssignType().hashCode());
        result = prime * result + ((getnRank() == null) ? 0 : getnRank().hashCode());
        result = prime * result + ((getnRankNature() == null) ? 0 : getnRankNature().hashCode());
        result = prime * result + ((getcUnit() == null) ? 0 : getcUnit().hashCode());
        result = prime * result + ((getcDepartment() == null) ? 0 : getcDepartment().hashCode());
        result = prime * result + ((getdAssignDate() == null) ? 0 : getdAssignDate().hashCode());
        result = prime * result + ((getnAssignReason() == null) ? 0 : getnAssignReason().hashCode());
        result = prime * result + ((getcApprovalUnit() == null) ? 0 : getcApprovalUnit().hashCode());
        result = prime * result + ((getcApprovalDocNo() == null) ? 0 : getcApprovalDocNo().hashCode());
        result = prime * result + ((getdApprovalDate() == null) ? 0 : getdApprovalDate().hashCode());
        result = prime * result + ((getRecordId() == null) ? 0 : getRecordId().hashCode());
        result = prime * result + ((getnPresentInfo() == null) ? 0 : getnPresentInfo().hashCode());
        result = prime * result + ((getCourtCode() == null) ? 0 : getCourtCode().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getnRankReport() == null) ? 0 : getnRankReport().hashCode());
        result = prime * result + ((getCourtNoText() == null) ? 0 : getCourtNoText().hashCode());
        result = prime * result + ((getnAssignTypeText() == null) ? 0 : getnAssignTypeText().hashCode());
        result = prime * result + ((getnRankText() == null) ? 0 : getnRankText().hashCode());
        result = prime * result + ((getnRankNatureText() == null) ? 0 : getnRankNatureText().hashCode());
        result = prime * result + ((getnAssignReasonText() == null) ? 0 : getnAssignReasonText().hashCode());
        result = prime * result + ((getnPresentInfoText() == null) ? 0 : getnPresentInfoText().hashCode());
        result = prime * result + ((getnRankReportText() == null) ? 0 : getnRankReportText().hashCode());
        return result;
    }
}