package cn.net.withub.ums.entity;

import java.util.Date;

public class UmsTrainingInfoView {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.id
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.user_id
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.sort_no
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private Integer sortNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.old_id
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private Long oldId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.court_no
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private Integer courtNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.user_no
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private Integer userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.court_code
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String courtCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.n_training_form
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String nTrainingForm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.c_other_training_form
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String cOtherTrainingForm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.c_class_name
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String cClassName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.d_start_date
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private Date dStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.d_end_date
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private Date dEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.n_specialty
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private Integer nSpecialty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.n_agency_type
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private Integer nAgencyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.c_other_agency_type
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String cOtherAgencyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.c_agency
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String cAgency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.n_duration
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private Integer nDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.c_result
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String cResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.n_training_way
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String nTrainingWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.n_training_type
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String nTrainingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.n_sync
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private Integer nSync;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.record_id
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.n_has_cert
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private Integer nHasCert;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.n_is_verified
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private Integer nIsVerified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.c_class_name_code
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String cClassNameCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.n_training_mode
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String nTrainingMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.c_agency_add
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String cAgencyAdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.n_duration_web
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private Integer nDurationWeb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.train_content
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String trainContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.bz
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.court_no_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String courtNoText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.n_training_form_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String nTrainingFormText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.n_specialty_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String nSpecialtyText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.n_agency_type_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String nAgencyTypeText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.n_training_way_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String nTrainingWayText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.n_training_type_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String nTrainingTypeText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.n_sync_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String nSyncText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.n_has_cert_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String nHasCertText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.c_class_name_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String cClassNameText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_training_info_view.n_is_verified_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    private String nIsVerifiedText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.id
     *
     * @return the value of ums_training_info_view.id
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.id
     *
     * @param id the value for ums_training_info_view.id
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.user_id
     *
     * @return the value of ums_training_info_view.user_id
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.user_id
     *
     * @param userId the value for ums_training_info_view.user_id
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.sort_no
     *
     * @return the value of ums_training_info_view.sort_no
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public Integer getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.sort_no
     *
     * @param sortNo the value for ums_training_info_view.sort_no
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setSortNo(Integer sortNo) {
        this.sortNo = sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.old_id
     *
     * @return the value of ums_training_info_view.old_id
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public Long getOldId() {
        return oldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.old_id
     *
     * @param oldId the value for ums_training_info_view.old_id
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setOldId(Long oldId) {
        this.oldId = oldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.court_no
     *
     * @return the value of ums_training_info_view.court_no
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public Integer getCourtNo() {
        return courtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.court_no
     *
     * @param courtNo the value for ums_training_info_view.court_no
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setCourtNo(Integer courtNo) {
        this.courtNo = courtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.user_no
     *
     * @return the value of ums_training_info_view.user_no
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public Integer getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.user_no
     *
     * @param userNo the value for ums_training_info_view.user_no
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setUserNo(Integer userNo) {
        this.userNo = userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.court_code
     *
     * @return the value of ums_training_info_view.court_code
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getCourtCode() {
        return courtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.court_code
     *
     * @param courtCode the value for ums_training_info_view.court_code
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setCourtCode(String courtCode) {
        this.courtCode = courtCode == null ? null : courtCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.n_training_form
     *
     * @return the value of ums_training_info_view.n_training_form
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getnTrainingForm() {
        return nTrainingForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.n_training_form
     *
     * @param nTrainingForm the value for ums_training_info_view.n_training_form
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setnTrainingForm(String nTrainingForm) {
        this.nTrainingForm = nTrainingForm == null ? null : nTrainingForm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.c_other_training_form
     *
     * @return the value of ums_training_info_view.c_other_training_form
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getcOtherTrainingForm() {
        return cOtherTrainingForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.c_other_training_form
     *
     * @param cOtherTrainingForm the value for ums_training_info_view.c_other_training_form
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setcOtherTrainingForm(String cOtherTrainingForm) {
        this.cOtherTrainingForm = cOtherTrainingForm == null ? null : cOtherTrainingForm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.c_class_name
     *
     * @return the value of ums_training_info_view.c_class_name
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getcClassName() {
        return cClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.c_class_name
     *
     * @param cClassName the value for ums_training_info_view.c_class_name
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setcClassName(String cClassName) {
        this.cClassName = cClassName == null ? null : cClassName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.d_start_date
     *
     * @return the value of ums_training_info_view.d_start_date
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public Date getdStartDate() {
        return dStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.d_start_date
     *
     * @param dStartDate the value for ums_training_info_view.d_start_date
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setdStartDate(Date dStartDate) {
        this.dStartDate = dStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.d_end_date
     *
     * @return the value of ums_training_info_view.d_end_date
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public Date getdEndDate() {
        return dEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.d_end_date
     *
     * @param dEndDate the value for ums_training_info_view.d_end_date
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setdEndDate(Date dEndDate) {
        this.dEndDate = dEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.n_specialty
     *
     * @return the value of ums_training_info_view.n_specialty
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public Integer getnSpecialty() {
        return nSpecialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.n_specialty
     *
     * @param nSpecialty the value for ums_training_info_view.n_specialty
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setnSpecialty(Integer nSpecialty) {
        this.nSpecialty = nSpecialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.n_agency_type
     *
     * @return the value of ums_training_info_view.n_agency_type
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public Integer getnAgencyType() {
        return nAgencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.n_agency_type
     *
     * @param nAgencyType the value for ums_training_info_view.n_agency_type
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setnAgencyType(Integer nAgencyType) {
        this.nAgencyType = nAgencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.c_other_agency_type
     *
     * @return the value of ums_training_info_view.c_other_agency_type
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getcOtherAgencyType() {
        return cOtherAgencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.c_other_agency_type
     *
     * @param cOtherAgencyType the value for ums_training_info_view.c_other_agency_type
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setcOtherAgencyType(String cOtherAgencyType) {
        this.cOtherAgencyType = cOtherAgencyType == null ? null : cOtherAgencyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.c_agency
     *
     * @return the value of ums_training_info_view.c_agency
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getcAgency() {
        return cAgency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.c_agency
     *
     * @param cAgency the value for ums_training_info_view.c_agency
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setcAgency(String cAgency) {
        this.cAgency = cAgency == null ? null : cAgency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.n_duration
     *
     * @return the value of ums_training_info_view.n_duration
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public Integer getnDuration() {
        return nDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.n_duration
     *
     * @param nDuration the value for ums_training_info_view.n_duration
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setnDuration(Integer nDuration) {
        this.nDuration = nDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.c_result
     *
     * @return the value of ums_training_info_view.c_result
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getcResult() {
        return cResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.c_result
     *
     * @param cResult the value for ums_training_info_view.c_result
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setcResult(String cResult) {
        this.cResult = cResult == null ? null : cResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.n_training_way
     *
     * @return the value of ums_training_info_view.n_training_way
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getnTrainingWay() {
        return nTrainingWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.n_training_way
     *
     * @param nTrainingWay the value for ums_training_info_view.n_training_way
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setnTrainingWay(String nTrainingWay) {
        this.nTrainingWay = nTrainingWay == null ? null : nTrainingWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.n_training_type
     *
     * @return the value of ums_training_info_view.n_training_type
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getnTrainingType() {
        return nTrainingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.n_training_type
     *
     * @param nTrainingType the value for ums_training_info_view.n_training_type
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setnTrainingType(String nTrainingType) {
        this.nTrainingType = nTrainingType == null ? null : nTrainingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.n_sync
     *
     * @return the value of ums_training_info_view.n_sync
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public Integer getnSync() {
        return nSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.n_sync
     *
     * @param nSync the value for ums_training_info_view.n_sync
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setnSync(Integer nSync) {
        this.nSync = nSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.record_id
     *
     * @return the value of ums_training_info_view.record_id
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.record_id
     *
     * @param recordId the value for ums_training_info_view.record_id
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId == null ? null : recordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.n_has_cert
     *
     * @return the value of ums_training_info_view.n_has_cert
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public Integer getnHasCert() {
        return nHasCert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.n_has_cert
     *
     * @param nHasCert the value for ums_training_info_view.n_has_cert
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setnHasCert(Integer nHasCert) {
        this.nHasCert = nHasCert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.n_is_verified
     *
     * @return the value of ums_training_info_view.n_is_verified
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public Integer getnIsVerified() {
        return nIsVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.n_is_verified
     *
     * @param nIsVerified the value for ums_training_info_view.n_is_verified
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setnIsVerified(Integer nIsVerified) {
        this.nIsVerified = nIsVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.c_class_name_code
     *
     * @return the value of ums_training_info_view.c_class_name_code
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getcClassNameCode() {
        return cClassNameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.c_class_name_code
     *
     * @param cClassNameCode the value for ums_training_info_view.c_class_name_code
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setcClassNameCode(String cClassNameCode) {
        this.cClassNameCode = cClassNameCode == null ? null : cClassNameCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.n_training_mode
     *
     * @return the value of ums_training_info_view.n_training_mode
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getnTrainingMode() {
        return nTrainingMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.n_training_mode
     *
     * @param nTrainingMode the value for ums_training_info_view.n_training_mode
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setnTrainingMode(String nTrainingMode) {
        this.nTrainingMode = nTrainingMode == null ? null : nTrainingMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.c_agency_add
     *
     * @return the value of ums_training_info_view.c_agency_add
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getcAgencyAdd() {
        return cAgencyAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.c_agency_add
     *
     * @param cAgencyAdd the value for ums_training_info_view.c_agency_add
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setcAgencyAdd(String cAgencyAdd) {
        this.cAgencyAdd = cAgencyAdd == null ? null : cAgencyAdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.n_duration_web
     *
     * @return the value of ums_training_info_view.n_duration_web
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public Integer getnDurationWeb() {
        return nDurationWeb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.n_duration_web
     *
     * @param nDurationWeb the value for ums_training_info_view.n_duration_web
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setnDurationWeb(Integer nDurationWeb) {
        this.nDurationWeb = nDurationWeb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.train_content
     *
     * @return the value of ums_training_info_view.train_content
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getTrainContent() {
        return trainContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.train_content
     *
     * @param trainContent the value for ums_training_info_view.train_content
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setTrainContent(String trainContent) {
        this.trainContent = trainContent == null ? null : trainContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.bz
     *
     * @return the value of ums_training_info_view.bz
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.bz
     *
     * @param bz the value for ums_training_info_view.bz
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.court_no_text
     *
     * @return the value of ums_training_info_view.court_no_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getCourtNoText() {
        return courtNoText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.court_no_text
     *
     * @param courtNoText the value for ums_training_info_view.court_no_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setCourtNoText(String courtNoText) {
        this.courtNoText = courtNoText == null ? null : courtNoText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.n_training_form_text
     *
     * @return the value of ums_training_info_view.n_training_form_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getnTrainingFormText() {
        return nTrainingFormText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.n_training_form_text
     *
     * @param nTrainingFormText the value for ums_training_info_view.n_training_form_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setnTrainingFormText(String nTrainingFormText) {
        this.nTrainingFormText = nTrainingFormText == null ? null : nTrainingFormText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.n_specialty_text
     *
     * @return the value of ums_training_info_view.n_specialty_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getnSpecialtyText() {
        return nSpecialtyText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.n_specialty_text
     *
     * @param nSpecialtyText the value for ums_training_info_view.n_specialty_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setnSpecialtyText(String nSpecialtyText) {
        this.nSpecialtyText = nSpecialtyText == null ? null : nSpecialtyText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.n_agency_type_text
     *
     * @return the value of ums_training_info_view.n_agency_type_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getnAgencyTypeText() {
        return nAgencyTypeText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.n_agency_type_text
     *
     * @param nAgencyTypeText the value for ums_training_info_view.n_agency_type_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setnAgencyTypeText(String nAgencyTypeText) {
        this.nAgencyTypeText = nAgencyTypeText == null ? null : nAgencyTypeText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.n_training_way_text
     *
     * @return the value of ums_training_info_view.n_training_way_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getnTrainingWayText() {
        return nTrainingWayText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.n_training_way_text
     *
     * @param nTrainingWayText the value for ums_training_info_view.n_training_way_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setnTrainingWayText(String nTrainingWayText) {
        this.nTrainingWayText = nTrainingWayText == null ? null : nTrainingWayText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.n_training_type_text
     *
     * @return the value of ums_training_info_view.n_training_type_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getnTrainingTypeText() {
        return nTrainingTypeText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.n_training_type_text
     *
     * @param nTrainingTypeText the value for ums_training_info_view.n_training_type_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setnTrainingTypeText(String nTrainingTypeText) {
        this.nTrainingTypeText = nTrainingTypeText == null ? null : nTrainingTypeText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.n_sync_text
     *
     * @return the value of ums_training_info_view.n_sync_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getnSyncText() {
        return nSyncText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.n_sync_text
     *
     * @param nSyncText the value for ums_training_info_view.n_sync_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setnSyncText(String nSyncText) {
        this.nSyncText = nSyncText == null ? null : nSyncText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.n_has_cert_text
     *
     * @return the value of ums_training_info_view.n_has_cert_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getnHasCertText() {
        return nHasCertText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.n_has_cert_text
     *
     * @param nHasCertText the value for ums_training_info_view.n_has_cert_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setnHasCertText(String nHasCertText) {
        this.nHasCertText = nHasCertText == null ? null : nHasCertText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.c_class_name_text
     *
     * @return the value of ums_training_info_view.c_class_name_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getcClassNameText() {
        return cClassNameText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.c_class_name_text
     *
     * @param cClassNameText the value for ums_training_info_view.c_class_name_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setcClassNameText(String cClassNameText) {
        this.cClassNameText = cClassNameText == null ? null : cClassNameText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_training_info_view.n_is_verified_text
     *
     * @return the value of ums_training_info_view.n_is_verified_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public String getnIsVerifiedText() {
        return nIsVerifiedText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_training_info_view.n_is_verified_text
     *
     * @param nIsVerifiedText the value for ums_training_info_view.n_is_verified_text
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    public void setnIsVerifiedText(String nIsVerifiedText) {
        this.nIsVerifiedText = nIsVerifiedText == null ? null : nIsVerifiedText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_training_info_view
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UmsTrainingInfoView other = (UmsTrainingInfoView) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getSortNo() == null ? other.getSortNo() == null : this.getSortNo().equals(other.getSortNo()))
            && (this.getOldId() == null ? other.getOldId() == null : this.getOldId().equals(other.getOldId()))
            && (this.getCourtNo() == null ? other.getCourtNo() == null : this.getCourtNo().equals(other.getCourtNo()))
            && (this.getUserNo() == null ? other.getUserNo() == null : this.getUserNo().equals(other.getUserNo()))
            && (this.getCourtCode() == null ? other.getCourtCode() == null : this.getCourtCode().equals(other.getCourtCode()))
            && (this.getnTrainingForm() == null ? other.getnTrainingForm() == null : this.getnTrainingForm().equals(other.getnTrainingForm()))
            && (this.getcOtherTrainingForm() == null ? other.getcOtherTrainingForm() == null : this.getcOtherTrainingForm().equals(other.getcOtherTrainingForm()))
            && (this.getcClassName() == null ? other.getcClassName() == null : this.getcClassName().equals(other.getcClassName()))
            && (this.getdStartDate() == null ? other.getdStartDate() == null : this.getdStartDate().equals(other.getdStartDate()))
            && (this.getdEndDate() == null ? other.getdEndDate() == null : this.getdEndDate().equals(other.getdEndDate()))
            && (this.getnSpecialty() == null ? other.getnSpecialty() == null : this.getnSpecialty().equals(other.getnSpecialty()))
            && (this.getnAgencyType() == null ? other.getnAgencyType() == null : this.getnAgencyType().equals(other.getnAgencyType()))
            && (this.getcOtherAgencyType() == null ? other.getcOtherAgencyType() == null : this.getcOtherAgencyType().equals(other.getcOtherAgencyType()))
            && (this.getcAgency() == null ? other.getcAgency() == null : this.getcAgency().equals(other.getcAgency()))
            && (this.getnDuration() == null ? other.getnDuration() == null : this.getnDuration().equals(other.getnDuration()))
            && (this.getcResult() == null ? other.getcResult() == null : this.getcResult().equals(other.getcResult()))
            && (this.getnTrainingWay() == null ? other.getnTrainingWay() == null : this.getnTrainingWay().equals(other.getnTrainingWay()))
            && (this.getnTrainingType() == null ? other.getnTrainingType() == null : this.getnTrainingType().equals(other.getnTrainingType()))
            && (this.getnSync() == null ? other.getnSync() == null : this.getnSync().equals(other.getnSync()))
            && (this.getRecordId() == null ? other.getRecordId() == null : this.getRecordId().equals(other.getRecordId()))
            && (this.getnHasCert() == null ? other.getnHasCert() == null : this.getnHasCert().equals(other.getnHasCert()))
            && (this.getnIsVerified() == null ? other.getnIsVerified() == null : this.getnIsVerified().equals(other.getnIsVerified()))
            && (this.getcClassNameCode() == null ? other.getcClassNameCode() == null : this.getcClassNameCode().equals(other.getcClassNameCode()))
            && (this.getnTrainingMode() == null ? other.getnTrainingMode() == null : this.getnTrainingMode().equals(other.getnTrainingMode()))
            && (this.getcAgencyAdd() == null ? other.getcAgencyAdd() == null : this.getcAgencyAdd().equals(other.getcAgencyAdd()))
            && (this.getnDurationWeb() == null ? other.getnDurationWeb() == null : this.getnDurationWeb().equals(other.getnDurationWeb()))
            && (this.getTrainContent() == null ? other.getTrainContent() == null : this.getTrainContent().equals(other.getTrainContent()))
            && (this.getBz() == null ? other.getBz() == null : this.getBz().equals(other.getBz()))
            && (this.getCourtNoText() == null ? other.getCourtNoText() == null : this.getCourtNoText().equals(other.getCourtNoText()))
            && (this.getnTrainingFormText() == null ? other.getnTrainingFormText() == null : this.getnTrainingFormText().equals(other.getnTrainingFormText()))
            && (this.getnSpecialtyText() == null ? other.getnSpecialtyText() == null : this.getnSpecialtyText().equals(other.getnSpecialtyText()))
            && (this.getnAgencyTypeText() == null ? other.getnAgencyTypeText() == null : this.getnAgencyTypeText().equals(other.getnAgencyTypeText()))
            && (this.getnTrainingWayText() == null ? other.getnTrainingWayText() == null : this.getnTrainingWayText().equals(other.getnTrainingWayText()))
            && (this.getnTrainingTypeText() == null ? other.getnTrainingTypeText() == null : this.getnTrainingTypeText().equals(other.getnTrainingTypeText()))
            && (this.getnSyncText() == null ? other.getnSyncText() == null : this.getnSyncText().equals(other.getnSyncText()))
            && (this.getnHasCertText() == null ? other.getnHasCertText() == null : this.getnHasCertText().equals(other.getnHasCertText()))
            && (this.getcClassNameText() == null ? other.getcClassNameText() == null : this.getcClassNameText().equals(other.getcClassNameText()))
            && (this.getnIsVerifiedText() == null ? other.getnIsVerifiedText() == null : this.getnIsVerifiedText().equals(other.getnIsVerifiedText()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_training_info_view
     *
     * @mbggenerated Wed Jun 06 18:24:21 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getSortNo() == null) ? 0 : getSortNo().hashCode());
        result = prime * result + ((getOldId() == null) ? 0 : getOldId().hashCode());
        result = prime * result + ((getCourtNo() == null) ? 0 : getCourtNo().hashCode());
        result = prime * result + ((getUserNo() == null) ? 0 : getUserNo().hashCode());
        result = prime * result + ((getCourtCode() == null) ? 0 : getCourtCode().hashCode());
        result = prime * result + ((getnTrainingForm() == null) ? 0 : getnTrainingForm().hashCode());
        result = prime * result + ((getcOtherTrainingForm() == null) ? 0 : getcOtherTrainingForm().hashCode());
        result = prime * result + ((getcClassName() == null) ? 0 : getcClassName().hashCode());
        result = prime * result + ((getdStartDate() == null) ? 0 : getdStartDate().hashCode());
        result = prime * result + ((getdEndDate() == null) ? 0 : getdEndDate().hashCode());
        result = prime * result + ((getnSpecialty() == null) ? 0 : getnSpecialty().hashCode());
        result = prime * result + ((getnAgencyType() == null) ? 0 : getnAgencyType().hashCode());
        result = prime * result + ((getcOtherAgencyType() == null) ? 0 : getcOtherAgencyType().hashCode());
        result = prime * result + ((getcAgency() == null) ? 0 : getcAgency().hashCode());
        result = prime * result + ((getnDuration() == null) ? 0 : getnDuration().hashCode());
        result = prime * result + ((getcResult() == null) ? 0 : getcResult().hashCode());
        result = prime * result + ((getnTrainingWay() == null) ? 0 : getnTrainingWay().hashCode());
        result = prime * result + ((getnTrainingType() == null) ? 0 : getnTrainingType().hashCode());
        result = prime * result + ((getnSync() == null) ? 0 : getnSync().hashCode());
        result = prime * result + ((getRecordId() == null) ? 0 : getRecordId().hashCode());
        result = prime * result + ((getnHasCert() == null) ? 0 : getnHasCert().hashCode());
        result = prime * result + ((getnIsVerified() == null) ? 0 : getnIsVerified().hashCode());
        result = prime * result + ((getcClassNameCode() == null) ? 0 : getcClassNameCode().hashCode());
        result = prime * result + ((getnTrainingMode() == null) ? 0 : getnTrainingMode().hashCode());
        result = prime * result + ((getcAgencyAdd() == null) ? 0 : getcAgencyAdd().hashCode());
        result = prime * result + ((getnDurationWeb() == null) ? 0 : getnDurationWeb().hashCode());
        result = prime * result + ((getTrainContent() == null) ? 0 : getTrainContent().hashCode());
        result = prime * result + ((getBz() == null) ? 0 : getBz().hashCode());
        result = prime * result + ((getCourtNoText() == null) ? 0 : getCourtNoText().hashCode());
        result = prime * result + ((getnTrainingFormText() == null) ? 0 : getnTrainingFormText().hashCode());
        result = prime * result + ((getnSpecialtyText() == null) ? 0 : getnSpecialtyText().hashCode());
        result = prime * result + ((getnAgencyTypeText() == null) ? 0 : getnAgencyTypeText().hashCode());
        result = prime * result + ((getnTrainingWayText() == null) ? 0 : getnTrainingWayText().hashCode());
        result = prime * result + ((getnTrainingTypeText() == null) ? 0 : getnTrainingTypeText().hashCode());
        result = prime * result + ((getnSyncText() == null) ? 0 : getnSyncText().hashCode());
        result = prime * result + ((getnHasCertText() == null) ? 0 : getnHasCertText().hashCode());
        result = prime * result + ((getcClassNameText() == null) ? 0 : getcClassNameText().hashCode());
        result = prime * result + ((getnIsVerifiedText() == null) ? 0 : getnIsVerifiedText().hashCode());
        return result;
    }
}