package cn.net.withub.ums.dao;

import cn.net.withub.ums.entity.UmsAbroadInfoView;
import cn.net.withub.ums.entity.UmsAbroadInfoViewCriteria;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UmsAbroadInfoViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_abroad_info_view
     *
     * @mbggenerated Wed May 16 17:21:54 CST 2018
     */
    int countByExample(UmsAbroadInfoViewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_abroad_info_view
     *
     * @mbggenerated Wed May 16 17:21:54 CST 2018
     */
    int deleteByExample(UmsAbroadInfoViewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_abroad_info_view
     *
     * @mbggenerated Wed May 16 17:21:54 CST 2018
     */
    int insert(UmsAbroadInfoView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_abroad_info_view
     *
     * @mbggenerated Wed May 16 17:21:54 CST 2018
     */
    int insertSelective(UmsAbroadInfoView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_abroad_info_view
     *
     * @mbggenerated Wed May 16 17:21:54 CST 2018
     */
    List<UmsAbroadInfoView> selectByExample(UmsAbroadInfoViewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_abroad_info_view
     *
     * @mbggenerated Wed May 16 17:21:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") UmsAbroadInfoView record, @Param("example") UmsAbroadInfoViewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_abroad_info_view
     *
     * @mbggenerated Wed May 16 17:21:54 CST 2018
     */
    int updateByExample(@Param("record") UmsAbroadInfoView record, @Param("example") UmsAbroadInfoViewCriteria example);
}