package cn.net.withub.ums.dao;

import cn.net.withub.ums.dao.attach.experimental.AttachedTableProvider;
import cn.net.withub.ums.entity.UmsCourtFull;
import cn.net.withub.ums.entity.UmsCourtFullCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.SelectProvider;

import java.util.List;
import java.util.Map;

public interface UmsCourtFullMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_court_full
     *
     * @mbggenerated Thu May 10 09:22:45 CST 2018
     */
    int countByExample(UmsCourtFullCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_court_full
     *
     * @mbggenerated Thu May 10 09:22:45 CST 2018
     */
    int deleteByExample(UmsCourtFullCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_court_full
     *
     * @mbggenerated Thu May 10 09:22:45 CST 2018
     */
    int deleteByPrimaryKey(String courtCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_court_full
     *
     * @mbggenerated Thu May 10 09:22:45 CST 2018
     */
    int insert(UmsCourtFull record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_court_full
     *
     * @mbggenerated Thu May 10 09:22:45 CST 2018
     */
    int insertSelective(UmsCourtFull record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_court_full
     *
     * @mbggenerated Thu May 10 09:22:45 CST 2018
     */
    List<UmsCourtFull> selectByExample(UmsCourtFullCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_court_full
     *
     * @mbggenerated Thu May 10 09:22:45 CST 2018
     */
    UmsCourtFull selectByPrimaryKey(String courtCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_court_full
     *
     * @mbggenerated Thu May 10 09:22:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") UmsCourtFull record, @Param("example") UmsCourtFullCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_court_full
     *
     * @mbggenerated Thu May 10 09:22:45 CST 2018
     */
    int updateByExample(@Param("record") UmsCourtFull record, @Param("example") UmsCourtFullCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_court_full
     *
     * @mbggenerated Thu May 10 09:22:45 CST 2018
     */
    int updateByPrimaryKeySelective(UmsCourtFull record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_court_full
     *
     * @mbggenerated Thu May 10 09:22:45 CST 2018
     */
    int updateByPrimaryKey(UmsCourtFull record);


    List<UmsCourtFull> selectByList(List courtList);

    List<UmsCourtFull> selectAllCourt();

    @SelectProvider(method = "getCourtByOrganization", type = AttachedTableProvider.class)
    @ResultMap("BaseResultMap")
    List<UmsCourtFull> getCourtByOrganization(List<String> courtList, List<Integer> codeList);


    List<UmsCourtFull> selectCourtForNOLeaderDept(Map<String,Object> map);

    int countCourtForNOLeaderDept(Map<String,Object> map);

}
