package cn.net.withub.ums.dao;

import cn.net.withub.ums.entity.UmsCode;
import cn.net.withub.ums.entity.UmsCodeCriteria;
import cn.net.withub.ums.entity.UmsCodeKey;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultType;
import org.apache.ibatis.annotations.Select;

import java.util.List;
import java.util.Map;

public interface UmsCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_code
     *
     * @mbggenerated Sat Apr 28 16:20:53 CST 2018
     */
    int countByExample(UmsCodeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_code
     *
     * @mbggenerated Sat Apr 28 16:20:53 CST 2018
     */
    int deleteByExample(UmsCodeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_code
     *
     * @mbggenerated Sat Apr 28 16:20:53 CST 2018
     */
    int deleteByPrimaryKey(UmsCodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_code
     *
     * @mbggenerated Sat Apr 28 16:20:53 CST 2018
     */
    int insert(UmsCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_code
     *
     * @mbggenerated Sat Apr 28 16:20:53 CST 2018
     */
    int insertSelective(UmsCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_code
     *
     * @mbggenerated Sat Apr 28 16:20:53 CST 2018
     */
    List<UmsCode> selectByExample(UmsCodeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_code
     *
     * @mbggenerated Sat Apr 28 16:20:53 CST 2018
     */
    UmsCode selectByPrimaryKey(UmsCodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_code
     *
     * @mbggenerated Sat Apr 28 16:20:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") UmsCode record, @Param("example") UmsCodeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_code
     *
     * @mbggenerated Sat Apr 28 16:20:53 CST 2018
     */
    int updateByExample(@Param("record") UmsCode record, @Param("example") UmsCodeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_code
     *
     * @mbggenerated Sat Apr 28 16:20:53 CST 2018
     */
    int updateByPrimaryKeySelective(UmsCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_code
     *
     * @mbggenerated Sat Apr 28 16:20:53 CST 2018
     */
    int updateByPrimaryKey(UmsCode record);

    //获取省份列表
    List<Map<String,Object>> getProvince();

    //获取城市列表
    List<Map<String,Object>> getCity(int provinceID);

    //获取区县列表
    List<Map<String,Object>> getArea(int cityID);

    List<Map<String, String>> getReport(int typeId);

    @Select("select column_name from information_schema.columns where table_name=#{tableName} and TABLE_SCHEMA='system_platform'")
    @ResultType(String.class)
    List<String> getTableColumn(@Param("tableName") String tableName);
}