package cn.net.withub.ums.dao;

import cn.net.withub.ums.entity.UmsDegreeInfoView;
import cn.net.withub.ums.entity.UmsDegreeInfoViewCriteria;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UmsDegreeInfoViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_degree_info_view
     *
     * @mbggenerated Wed May 16 17:21:54 CST 2018
     */
    int countByExample(UmsDegreeInfoViewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_degree_info_view
     *
     * @mbggenerated Wed May 16 17:21:54 CST 2018
     */
    int deleteByExample(UmsDegreeInfoViewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_degree_info_view
     *
     * @mbggenerated Wed May 16 17:21:54 CST 2018
     */
    int insert(UmsDegreeInfoView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_degree_info_view
     *
     * @mbggenerated Wed May 16 17:21:54 CST 2018
     */
    int insertSelective(UmsDegreeInfoView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_degree_info_view
     *
     * @mbggenerated Wed May 16 17:21:54 CST 2018
     */
    List<UmsDegreeInfoView> selectByExample(UmsDegreeInfoViewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_degree_info_view
     *
     * @mbggenerated Wed May 16 17:21:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") UmsDegreeInfoView record, @Param("example") UmsDegreeInfoViewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_degree_info_view
     *
     * @mbggenerated Wed May 16 17:21:54 CST 2018
     */
    int updateByExample(@Param("record") UmsDegreeInfoView record, @Param("example") UmsDegreeInfoViewCriteria example);
}