package cn.net.withub.ums.dao;

import cn.net.withub.ums.entity.UmsDepartment;
import cn.net.withub.ums.entity.UmsDepartmentCriteria;
import cn.net.withub.ums.entity.UmsDepartmentKey;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;
import java.util.Map;

public interface UmsDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_department
     *
     * @mbggenerated Thu May 10 17:28:47 CST 2018
     */
    int countByExample(UmsDepartmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_department
     *
     * @mbggenerated Thu May 10 17:28:47 CST 2018
     */
    int deleteByExample(UmsDepartmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_department
     *
     * @mbggenerated Thu May 10 17:28:47 CST 2018
     */
    int deleteByPrimaryKey(UmsDepartmentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_department
     *
     * @mbggenerated Thu May 10 17:28:47 CST 2018
     */
    int insert(UmsDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_department
     *
     * @mbggenerated Thu May 10 17:28:47 CST 2018
     */
    int insertSelective(UmsDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_department
     *
     * @mbggenerated Thu May 10 17:28:47 CST 2018
     */
    List<UmsDepartment> selectByExample(UmsDepartmentCriteria example);

    List<UmsDepartment> selectByExample(UmsDepartmentCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_department
     *
     * @mbggenerated Thu May 10 17:28:47 CST 2018
     */
    UmsDepartment selectByPrimaryKey(UmsDepartmentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_department
     *
     * @mbggenerated Thu May 10 17:28:47 CST 2018
     */
    int updateByExampleSelective(@Param("record") UmsDepartment record, @Param("example") UmsDepartmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_department
     *
     * @mbggenerated Thu May 10 17:28:47 CST 2018
     */
    int updateByExample(@Param("record") UmsDepartment record, @Param("example") UmsDepartmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_department
     *
     * @mbggenerated Thu May 10 17:28:47 CST 2018
     */
    int updateByPrimaryKeySelective(UmsDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_department
     *
     * @mbggenerated Thu May 10 17:28:47 CST 2018
     */
    int updateByPrimaryKey(UmsDepartment record);

    Integer selectMaxDeptNo(Map map);

    Integer selectMaxSortNo(Map map);

    List<Integer> getLevelDeptNo(Map map);

    int updateDeptSort(Map map);

    Integer countByCourtNo(@Param("courtNo") Integer courtNo);
}
