package cn.net.withub.ums.dao;

import cn.net.withub.ums.entity.UmsExternalCompanyInfo;
import cn.net.withub.ums.entity.UmsExternalCompanyInfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsExternalCompanyInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_external_company_info
     *
     * @mbggenerated
     */
    int countByExample(UmsExternalCompanyInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_external_company_info
     *
     * @mbggenerated
     */
    int deleteByExample(UmsExternalCompanyInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_external_company_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_external_company_info
     *
     * @mbggenerated
     */
    int insert(UmsExternalCompanyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_external_company_info
     *
     * @mbggenerated
     */
    int insertSelective(UmsExternalCompanyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_external_company_info
     *
     * @mbggenerated
     */
    List<UmsExternalCompanyInfo> selectByExample(UmsExternalCompanyInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_external_company_info
     *
     * @mbggenerated
     */
    UmsExternalCompanyInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_external_company_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UmsExternalCompanyInfo record, @Param("example") UmsExternalCompanyInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_external_company_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UmsExternalCompanyInfo record, @Param("example") UmsExternalCompanyInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_external_company_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UmsExternalCompanyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_external_company_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UmsExternalCompanyInfo record);
}