package cn.net.withub.ums.dao;

import cn.net.withub.ums.entity.UmsLegalJob;
import cn.net.withub.ums.entity.UmsLegalJobCriteria;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UmsLegalJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:32:56 CST 2018
     */
    int countByExample(UmsLegalJobCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:32:56 CST 2018
     */
    int deleteByExample(UmsLegalJobCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:32:56 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:32:56 CST 2018
     */
    int insert(UmsLegalJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:32:56 CST 2018
     */
    int insertSelective(UmsLegalJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:32:56 CST 2018
     */
    List<UmsLegalJob> selectByExample(UmsLegalJobCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:32:56 CST 2018
     */
    UmsLegalJob selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:32:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") UmsLegalJob record, @Param("example") UmsLegalJobCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:32:56 CST 2018
     */
    int updateByExample(@Param("record") UmsLegalJob record, @Param("example") UmsLegalJobCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:32:56 CST 2018
     */
    int updateByPrimaryKeySelective(UmsLegalJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_legal_job
     *
     * @mbggenerated Fri Jun 08 16:32:56 CST 2018
     */
    int updateByPrimaryKey(UmsLegalJob record);

    int updateUmsUserInfo(UmsLegalJob record);

    int updateXtptUserInfo(UmsLegalJob record);
}