package cn.net.withub.ums.dao;

import cn.net.withub.ums.entity.UmsProTechnicalPosition;
import cn.net.withub.ums.entity.UmsProTechnicalPositionCriteria;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UmsProTechnicalPositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:21:54 CST 2018
     */
    int countByExample(UmsProTechnicalPositionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:21:54 CST 2018
     */
    int deleteByExample(UmsProTechnicalPositionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:21:54 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:21:54 CST 2018
     */
    int insert(UmsProTechnicalPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:21:54 CST 2018
     */
    int insertSelective(UmsProTechnicalPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:21:54 CST 2018
     */
    List<UmsProTechnicalPosition> selectByExample(UmsProTechnicalPositionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:21:54 CST 2018
     */
    UmsProTechnicalPosition selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:21:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") UmsProTechnicalPosition record, @Param("example") UmsProTechnicalPositionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:21:54 CST 2018
     */
    int updateByExample(@Param("record") UmsProTechnicalPosition record, @Param("example") UmsProTechnicalPositionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:21:54 CST 2018
     */
    int updateByPrimaryKeySelective(UmsProTechnicalPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_pro_technical_position
     *
     * @mbggenerated Wed May 16 17:21:54 CST 2018
     */
    int updateByPrimaryKey(UmsProTechnicalPosition record);
}