package cn.net.withub.ums.dao;

import cn.net.withub.ums.entity.UmsPhoto;
import cn.net.withub.ums.entity.UmsPhotoCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;
import java.util.Map;

public interface UmsPhotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_photo
     *
     * @mbggenerated
     */
    int countByExample(UmsPhotoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_photo
     *
     * @mbggenerated
     */
    int deleteByExample(UmsPhotoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_photo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_photo
     *
     * @mbggenerated
     */
    int insert(UmsPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_photo
     *
     * @mbggenerated
     */
    int insertSelective(UmsPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_photo
     *
     * @mbggenerated
     */
    List<UmsPhoto> selectByExampleWithBLOBs(UmsPhotoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_photo
     *
     * @mbggenerated
     */
    List<UmsPhoto> selectByExample(UmsPhotoCriteria example);


    List<UmsPhoto> selectByExample(UmsPhotoCriteria example,RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_photo
     *
     * @mbggenerated
     */
    UmsPhoto selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_photo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UmsPhoto record, @Param("example") UmsPhotoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_photo
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") UmsPhoto record, @Param("example") UmsPhotoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_photo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UmsPhoto record, @Param("example") UmsPhotoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_photo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UmsPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_photo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(UmsPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_photo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UmsPhoto record);


    List<String> selectIsValidUser(RowBounds rowBounds);

    List<Map> selectByDept(Map map);
}
