package cn.net.withub.ums.dao;

import cn.net.withub.ums.entity.UmsRewardInfo;
import cn.net.withub.ums.entity.UmsRewardInfoCriteria;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UmsRewardInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_reward_info
     *
     * @mbggenerated Tue Jun 05 15:21:55 CST 2018
     */
    int countByExample(UmsRewardInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_reward_info
     *
     * @mbggenerated Tue Jun 05 15:21:55 CST 2018
     */
    int deleteByExample(UmsRewardInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_reward_info
     *
     * @mbggenerated Tue Jun 05 15:21:55 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_reward_info
     *
     * @mbggenerated Tue Jun 05 15:21:55 CST 2018
     */
    int insert(UmsRewardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_reward_info
     *
     * @mbggenerated Tue Jun 05 15:21:55 CST 2018
     */
    int insertSelective(UmsRewardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_reward_info
     *
     * @mbggenerated Tue Jun 05 15:21:55 CST 2018
     */
    List<UmsRewardInfo> selectByExample(UmsRewardInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_reward_info
     *
     * @mbggenerated Tue Jun 05 15:21:55 CST 2018
     */
    UmsRewardInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_reward_info
     *
     * @mbggenerated Tue Jun 05 15:21:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") UmsRewardInfo record, @Param("example") UmsRewardInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_reward_info
     *
     * @mbggenerated Tue Jun 05 15:21:55 CST 2018
     */
    int updateByExample(@Param("record") UmsRewardInfo record, @Param("example") UmsRewardInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_reward_info
     *
     * @mbggenerated Tue Jun 05 15:21:55 CST 2018
     */
    int updateByPrimaryKeySelective(UmsRewardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_reward_info
     *
     * @mbggenerated Tue Jun 05 15:21:55 CST 2018
     */
    int updateByPrimaryKey(UmsRewardInfo record);
}