package cn.net.withub.ums.dao;

import cn.net.withub.ums.entity.UmsRoleMenuAuthCriteria;
import cn.net.withub.ums.entity.UmsRoleMenuAuthKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsRoleMenuAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_menu_auth
     *
     * @mbggenerated
     */
    int countByExample(UmsRoleMenuAuthCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_menu_auth
     *
     * @mbggenerated
     */
    int deleteByExample(UmsRoleMenuAuthCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_menu_auth
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(UmsRoleMenuAuthKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_menu_auth
     *
     * @mbggenerated
     */
    int insert(UmsRoleMenuAuthKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_menu_auth
     *
     * @mbggenerated
     */
    int insertSelective(UmsRoleMenuAuthKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_menu_auth
     *
     * @mbggenerated
     */
    List<UmsRoleMenuAuthKey> selectByExample(UmsRoleMenuAuthCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_menu_auth
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UmsRoleMenuAuthKey record, @Param("example") UmsRoleMenuAuthCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_menu_auth
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UmsRoleMenuAuthKey record, @Param("example") UmsRoleMenuAuthCriteria example);
}