package cn.net.withub.ums.dao;

import cn.net.withub.ums.entity.UmsTemporaryPosition;
import cn.net.withub.ums.entity.UmsTemporaryPositionExample;
import cn.net.withub.ums.entity.UmsTemporaryPositionKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface UmsTemporaryPositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_temporary_position
     *
     * @mbggenerated Thu Mar 30 16:39:45 CST 2017
     */
    int countByExample(UmsTemporaryPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_temporary_position
     *
     * @mbggenerated Thu Mar 30 16:39:45 CST 2017
     */
    int deleteByExample(UmsTemporaryPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_temporary_position
     *
     * @mbggenerated Thu Mar 30 16:39:45 CST 2017
     */
    int deleteByPrimaryKey(UmsTemporaryPositionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_temporary_position
     *
     * @mbggenerated Thu Mar 30 16:39:45 CST 2017
     */
    int insert(UmsTemporaryPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_temporary_position
     *
     * @mbggenerated Thu Mar 30 16:39:45 CST 2017
     */
    int insertSelective(UmsTemporaryPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_temporary_position
     *
     * @mbggenerated Thu Mar 30 16:39:45 CST 2017
     */
    List<UmsTemporaryPosition> selectByExample(UmsTemporaryPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_temporary_position
     *
     * @mbggenerated Thu Mar 30 16:39:45 CST 2017
     */
    UmsTemporaryPosition selectByPrimaryKey(UmsTemporaryPositionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_temporary_position
     *
     * @mbggenerated Thu Mar 30 16:39:45 CST 2017
     */
    int updateByExampleSelective(@Param("record") UmsTemporaryPosition record, @Param("example") UmsTemporaryPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_temporary_position
     *
     * @mbggenerated Thu Mar 30 16:39:45 CST 2017
     */
    int updateByExample(@Param("record") UmsTemporaryPosition record, @Param("example") UmsTemporaryPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_temporary_position
     *
     * @mbggenerated Thu Mar 30 16:39:45 CST 2017
     */
    int updateByPrimaryKeySelective(UmsTemporaryPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_temporary_position
     *
     * @mbggenerated Thu Mar 30 16:39:45 CST 2017
     */
    int updateByPrimaryKey(UmsTemporaryPosition record);

    List<Map> selectViewByExample(UmsTemporaryPositionExample example);

    int deleteByUUID(UmsTemporaryPosition entity);

    int updatePartTimeJob(Map map);
}