package cn.net.withub.ums.dao;

import cn.net.withub.ums.entity.UmsWageInfo;
import cn.net.withub.ums.entity.UmsWageInfoCriteria;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UmsWageInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_wage_info
     *
     * @mbggenerated Tue Jun 05 15:21:55 CST 2018
     */
    int countByExample(UmsWageInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_wage_info
     *
     * @mbggenerated Tue Jun 05 15:21:55 CST 2018
     */
    int deleteByExample(UmsWageInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_wage_info
     *
     * @mbggenerated Tue Jun 05 15:21:55 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_wage_info
     *
     * @mbggenerated Tue Jun 05 15:21:55 CST 2018
     */
    int insert(UmsWageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_wage_info
     *
     * @mbggenerated Tue Jun 05 15:21:55 CST 2018
     */
    int insertSelective(UmsWageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_wage_info
     *
     * @mbggenerated Tue Jun 05 15:21:55 CST 2018
     */
    List<UmsWageInfo> selectByExample(UmsWageInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_wage_info
     *
     * @mbggenerated Tue Jun 05 15:21:55 CST 2018
     */
    UmsWageInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_wage_info
     *
     * @mbggenerated Tue Jun 05 15:21:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") UmsWageInfo record, @Param("example") UmsWageInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_wage_info
     *
     * @mbggenerated Tue Jun 05 15:21:55 CST 2018
     */
    int updateByExample(@Param("record") UmsWageInfo record, @Param("example") UmsWageInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_wage_info
     *
     * @mbggenerated Tue Jun 05 15:21:55 CST 2018
     */
    int updateByPrimaryKeySelective(UmsWageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_wage_info
     *
     * @mbggenerated Tue Jun 05 15:21:55 CST 2018
     */
    int updateByPrimaryKey(UmsWageInfo record);
}