package cn.net.withub.ums.dao;

import cn.net.withub.ums.entity.XtptBmDepartement;
import cn.net.withub.ums.entity.XtptBmDepartementExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface XtptBmDepartementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpt_bm_departement
     *
     * @mbggenerated Fri Jan 08 17:26:38 CST 2016
     */
    int countByExample(XtptBmDepartementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpt_bm_departement
     *
     * @mbggenerated Fri Jan 08 17:26:38 CST 2016
     */
    int deleteByExample(XtptBmDepartementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpt_bm_departement
     *
     * @mbggenerated Fri Jan 08 17:26:38 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpt_bm_departement
     *
     * @mbggenerated Fri Jan 08 17:26:38 CST 2016
     */
    int insert(XtptBmDepartement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpt_bm_departement
     *
     * @mbggenerated Fri Jan 08 17:26:38 CST 2016
     */
    int insertSelective(XtptBmDepartement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpt_bm_departement
     *
     * @mbggenerated Fri Jan 08 17:26:38 CST 2016
     */
    List<XtptBmDepartement> selectByExample(XtptBmDepartementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpt_bm_departement
     *
     * @mbggenerated Fri Jan 08 17:26:38 CST 2016
     */
    XtptBmDepartement selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpt_bm_departement
     *
     * @mbggenerated Fri Jan 08 17:26:38 CST 2016
     */
    int updateByExampleSelective(@Param("record") XtptBmDepartement record, @Param("example") XtptBmDepartementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpt_bm_departement
     *
     * @mbggenerated Fri Jan 08 17:26:38 CST 2016
     */
    int updateByExample(@Param("record") XtptBmDepartement record, @Param("example") XtptBmDepartementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpt_bm_departement
     *
     * @mbggenerated Fri Jan 08 17:26:38 CST 2016
     */
    int updateByPrimaryKeySelective(XtptBmDepartement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpt_bm_departement
     *
     * @mbggenerated Fri Jan 08 17:26:38 CST 2016
     */
    int updateByPrimaryKey(XtptBmDepartement record);

    List<XtptBmDepartement> selectDistinctAllUser(Map param);
}
