package cn.net.withub.ums.dao;

import cn.net.withub.ums.entity.XtptTUserDuplicate;
import cn.net.withub.ums.entity.XtptTUserDuplicateExample;
import cn.net.withub.ums.entity.XtptUser;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface XtptTUserDuplicateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpt_t_user_duplicate
     *
     * @mbggenerated Fri Jan 01 15:21:20 CST 2016
     */
    int countByExample(XtptTUserDuplicateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpt_t_user_duplicate
     *
     * @mbggenerated Fri Jan 01 15:21:20 CST 2016
     */
    int deleteByExample(XtptTUserDuplicateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpt_t_user_duplicate
     *
     * @mbggenerated Fri Jan 01 15:21:20 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpt_t_user_duplicate
     *
     * @mbggenerated Fri Jan 01 15:21:20 CST 2016
     */
    int insert(XtptTUserDuplicate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpt_t_user_duplicate
     *
     * @mbggenerated Fri Jan 01 15:21:20 CST 2016
     */
    int insertSelective(XtptTUserDuplicate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpt_t_user_duplicate
     *
     * @mbggenerated Fri Jan 01 15:21:20 CST 2016
     */
    List<XtptTUserDuplicate> selectByExample(XtptTUserDuplicateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpt_t_user_duplicate
     *
     * @mbggenerated Fri Jan 01 15:21:20 CST 2016
     */
    XtptTUserDuplicate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpt_t_user_duplicate
     *
     * @mbggenerated Fri Jan 01 15:21:20 CST 2016
     */
    int updateByExampleSelective(@Param("record") XtptTUserDuplicate record, @Param("example") XtptTUserDuplicateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpt_t_user_duplicate
     *
     * @mbggenerated Fri Jan 01 15:21:20 CST 2016
     */
    int updateByExample(@Param("record") XtptTUserDuplicate record, @Param("example") XtptTUserDuplicateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpt_t_user_duplicate
     *
     * @mbggenerated Fri Jan 01 15:21:20 CST 2016
     */
    int updateByPrimaryKeySelective(XtptTUserDuplicate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xtpt_t_user_duplicate
     *
     * @mbggenerated Fri Jan 01 15:21:20 CST 2016
     */
    int updateByPrimaryKey(XtptTUserDuplicate record);

    int deleteByUUID(XtptTUserDuplicate entity);

    int insertForXtptUser(XtptUser entity);
}
