package cn.net.withub.ums.action.juror;

/**
 * Created by Administrator on 2016/3/22.
 */
import java.util.Date;

//用于陪审员对接数据
public class JurorUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juror_user.full_name
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    private String fullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juror_user.gender
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juror_user.birthday
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juror_user.idcard
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juror_user.nation
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    private Integer nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juror_user.education
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    private Integer education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juror_user.political
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    private Integer political;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juror_user.local_address
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    private String localAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juror_user.machine_number
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    private String machineNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juror_user.phone_number
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juror_user.mail
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juror_user.address_type
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    private Integer addressType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juror_user.juror_work
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    private String jurorWork;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juror_user.company
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juror_user.work_area_one
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    private Integer workAreaOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juror_user.work_area_two
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    private Integer workAreaTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juror_user.work_area_three
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    private Integer workAreaThree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juror_user.work_area_four
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    private Integer workAreaFour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juror_user.specialty
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    private String specialty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juror_user.begin_time
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juror_user.is_new
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    private Integer isNew;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juror_user.juror_number
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    private Integer jurorNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juror_user.case_type
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    private String caseType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juror_user.full_name
     *
     * @return the value of juror_user.full_name
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juror_user.full_name
     *
     * @param fullName the value for juror_user.full_name
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juror_user.gender
     *
     * @return the value of juror_user.gender
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juror_user.gender
     *
     * @param gender the value for juror_user.gender
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juror_user.birthday
     *
     * @return the value of juror_user.birthday
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juror_user.birthday
     *
     * @param birthday the value for juror_user.birthday
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juror_user.idcard
     *
     * @return the value of juror_user.idcard
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juror_user.idcard
     *
     * @param idcard the value for juror_user.idcard
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juror_user.nation
     *
     * @return the value of juror_user.nation
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public Integer getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juror_user.nation
     *
     * @param nation the value for juror_user.nation
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public void setNation(Integer nation) {
        this.nation = nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juror_user.education
     *
     * @return the value of juror_user.education
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public Integer getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juror_user.education
     *
     * @param education the value for juror_user.education
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public void setEducation(Integer education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juror_user.political
     *
     * @return the value of juror_user.political
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public Integer getPolitical() {
        return political;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juror_user.political
     *
     * @param political the value for juror_user.political
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public void setPolitical(Integer political) {
        this.political = political;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juror_user.local_address
     *
     * @return the value of juror_user.local_address
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public String getLocalAddress() {
        return localAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juror_user.local_address
     *
     * @param localAddress the value for juror_user.local_address
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public void setLocalAddress(String localAddress) {
        this.localAddress = localAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juror_user.machine_number
     *
     * @return the value of juror_user.machine_number
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public String getMachineNumber() {
        return machineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juror_user.machine_number
     *
     * @param machineNumber the value for juror_user.machine_number
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public void setMachineNumber(String machineNumber) {
        this.machineNumber = machineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juror_user.phone_number
     *
     * @return the value of juror_user.phone_number
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juror_user.phone_number
     *
     * @param phoneNumber the value for juror_user.phone_number
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juror_user.mail
     *
     * @return the value of juror_user.mail
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juror_user.mail
     *
     * @param mail the value for juror_user.mail
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juror_user.address_type
     *
     * @return the value of juror_user.address_type
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public Integer getAddressType() {
        return addressType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juror_user.address_type
     *
     * @param addressType the value for juror_user.address_type
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public void setAddressType(Integer addressType) {
        this.addressType = addressType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juror_user.juror_work
     *
     * @return the value of juror_user.juror_work
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public String getJurorWork() {
        return jurorWork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juror_user.juror_work
     *
     * @param jurorWork the value for juror_user.juror_work
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public void setJurorWork(String jurorWork) {
        this.jurorWork = jurorWork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juror_user.company
     *
     * @return the value of juror_user.company
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juror_user.company
     *
     * @param company the value for juror_user.company
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juror_user.work_area_one
     *
     * @return the value of juror_user.work_area_one
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public Integer getWorkAreaOne() {
        return workAreaOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juror_user.work_area_one
     *
     * @param workAreaOne the value for juror_user.work_area_one
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public void setWorkAreaOne(Integer workAreaOne) {
        this.workAreaOne = workAreaOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juror_user.work_area_two
     *
     * @return the value of juror_user.work_area_two
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public Integer getWorkAreaTwo() {
        return workAreaTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juror_user.work_area_two
     *
     * @param workAreaTwo the value for juror_user.work_area_two
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public void setWorkAreaTwo(Integer workAreaTwo) {
        this.workAreaTwo = workAreaTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juror_user.work_area_three
     *
     * @return the value of juror_user.work_area_three
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public Integer getWorkAreaThree() {
        return workAreaThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juror_user.work_area_three
     *
     * @param workAreaThree the value for juror_user.work_area_three
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public void setWorkAreaThree(Integer workAreaThree) {
        this.workAreaThree = workAreaThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juror_user.work_area_four
     *
     * @return the value of juror_user.work_area_four
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public Integer getWorkAreaFour() {
        return workAreaFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juror_user.work_area_four
     *
     * @param workAreaFour the value for juror_user.work_area_four
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public void setWorkAreaFour(Integer workAreaFour) {
        this.workAreaFour = workAreaFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juror_user.specialty
     *
     * @return the value of juror_user.specialty
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public String getSpecialty() {
        return specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juror_user.specialty
     *
     * @param specialty the value for juror_user.specialty
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public void setSpecialty(String specialty) {
        this.specialty = specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juror_user.begin_time
     *
     * @return the value of juror_user.begin_time
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juror_user.begin_time
     *
     * @param beginTime the value for juror_user.begin_time
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juror_user.is_new
     *
     * @return the value of juror_user.is_new
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public Integer getIsNew() {
        return isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juror_user.is_new
     *
     * @param isNew the value for juror_user.is_new
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public void setIsNew(Integer isNew) {
        this.isNew = isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juror_user.juror_number
     *
     * @return the value of juror_user.juror_number
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public Integer getJurorNumber() {
        return jurorNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juror_user.juror_number
     *
     * @param jurorNumber the value for juror_user.juror_number
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public void setJurorNumber(Integer jurorNumber) {
        this.jurorNumber = jurorNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juror_user.case_type
     *
     * @return the value of juror_user.case_type
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public String getCaseType() {
        return caseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juror_user.case_type
     *
     * @param caseType the value for juror_user.case_type
     *
     * @mbggenerated Tue Mar 22 10:00:17 CST 2016
     */
    public void setCaseType(String caseType) {
        this.caseType = caseType;
    }
}
